public const string alternate_air_off_1 = "sim/altair/alternate_air_off_1";                     //Alternate air #1 off.
public const string alternate_air_off_2 = "sim/altair/alternate_air_off_2";                     //Alternate air #2 off.
public const string alternate_air_off_3 = "sim/altair/alternate_air_off_3";                     //Alternate air #3 off.
public const string alternate_air_off_4 = "sim/altair/alternate_air_off_4";                     //Alternate air #4 off.
public const string alternate_air_off_5 = "sim/altair/alternate_air_off_5";                     //Alternate air #5 off.
public const string alternate_air_off_6 = "sim/altair/alternate_air_off_6";                     //Alternate air #6 off.
public const string alternate_air_off_7 = "sim/altair/alternate_air_off_7";                     //Alternate air #7 off.
public const string alternate_air_off_8 = "sim/altair/alternate_air_off_8";                     //Alternate air #8 off.
public const string alternate_air_on_1 = "sim/altair/alternate_air_on_1";                      //Alternate air #1 on.
public const string alternate_air_on_2 = "sim/altair/alternate_air_on_2";                      //Alternate air #2 on.
public const string alternate_air_on_3 = "sim/altair/alternate_air_on_3";                      //Alternate air #3 on.
public const string alternate_air_on_4 = "sim/altair/alternate_air_on_4";                      //Alternate air #4 on.
public const string alternate_air_on_5 = "sim/altair/alternate_air_on_5";                      //Alternate air #5 on.
public const string alternate_air_on_6 = "sim/altair/alternate_air_on_6";                      //Alternate air #6 on.
public const string alternate_air_on_7 = "sim/altair/alternate_air_on_7";                      //Alternate air #7 on.
public const string alternate_air_on_8 = "sim/altair/alternate_air_on_8";                      //Alternate air #8 on.
public const string alternate_air_backup_off_1 = "sim/altair/alternate_air_backup_off_1";              //Alternate air backup #1 off.
public const string alternate_air_backup_off_2 = "sim/altair/alternate_air_backup_off_2";              //Alternate air backup #2 off.
public const string alternate_air_backup_off_3 = "sim/altair/alternate_air_backup_off_3";              //Alternate air backup #3 off.
public const string alternate_air_backup_off_4 = "sim/altair/alternate_air_backup_off_4";              //Alternate air backup #4 off.
public const string alternate_air_backup_off_5 = "sim/altair/alternate_air_backup_off_5";              //Alternate air backup #5 off.
public const string alternate_air_backup_off_6 = "sim/altair/alternate_air_backup_off_6";              //Alternate air backup #6 off.
public const string alternate_air_backup_off_7 = "sim/altair/alternate_air_backup_off_7";              //Alternate air backup #7 off.
public const string alternate_air_backup_off_8 = "sim/altair/alternate_air_backup_off_8";              //Alternate air backup #8 off.
public const string alternate_air_backup_on_1 = "sim/altair/alternate_air_backup_on_1";               //Alternate air backup #1 on.
public const string alternate_air_backup_on_2 = "sim/altair/alternate_air_backup_on_2";               //Alternate air backup #2 on.
public const string alternate_air_backup_on_3 = "sim/altair/alternate_air_backup_on_3";               //Alternate air backup #3 on.
public const string alternate_air_backup_on_4 = "sim/altair/alternate_air_backup_on_4";               //Alternate air backup #4 on.
public const string alternate_air_backup_on_5 = "sim/altair/alternate_air_backup_on_5";               //Alternate air backup #5 on.
public const string alternate_air_backup_on_6 = "sim/altair/alternate_air_backup_on_6";               //Alternate air backup #6 on.
public const string alternate_air_backup_on_7 = "sim/altair/alternate_air_backup_on_7";               //Alternate air backup #7 on.
public const string alternate_air_backup_on_8 = "sim/altair/alternate_air_backup_on_8";               //Alternate air backup #8 on.