public const string test_all_annunciators = "sim/annunciator/test_all_annunciators";           //Test all annunciators.
public const string test_stall = "sim/annunciator/test_stall";           //Test stall warn.
public const string test_fire_1_annun = "sim/annunciator/test_fire_1_annun";           //Test fire 1 annunciator.
public const string test_fire_2_annun = "sim/annunciator/test_fire_2_annun";           //Test fire 2 annunciator.
public const string test_fire_3_annun = "sim/annunciator/test_fire_3_annun";           //Test fire 3 annunciator.
public const string test_fire_4_annun = "sim/annunciator/test_fire_4_annun";           //Test fire 4 annunciator.
public const string test_fire_5_annun = "sim/annunciator/test_fire_5_annun";           //Test fire 5 annunciator.
public const string test_fire_6_annun = "sim/annunciator/test_fire_6_annun";           //Test fire 6 annunciator.
public const string test_fire_7_annun = "sim/annunciator/test_fire_7_annun";           //Test fire 7 annunciator.
public const string test_fire_8_annun = "sim/annunciator/test_fire_8_annun";           //Test fire 8 annunciator.
public const string clear_master_caution = "sim/annunciator/clear_master_caution";           //Clear master caution.
public const string clear_master_warning = "sim/annunciator/clear_master_warning";           //Clear master warning.
public const string clear_master_accept = "sim/annunciator/clear_master_accept";           //Clear master accept.
public const string gear_warning_mute = "sim/annunciator/gear_warning_mute";           //Mute gear warning horn.
public const string marker_beacon_mute = "sim/annunciator/marker_beacon_mute";           //Mute marker beacons.