public const string hsi_select_down = "sim/autopilot/hsi_select_down";           //HSI select down one.
public const string hsi_select_up = "sim/autopilot/hsi_select_up";           //HSI select up one.
public const string hsi_select_nav_1 = "sim/autopilot/hsi_select_nav_1";           //HSI shows NAV 1.
public const string hsi_select_nav_2 = "sim/autopilot/hsi_select_nav_2";           //HSI shows NAV 2.
public const string hsi_select_gps = "sim/autopilot/hsi_select_gps";           //HSI shows GPS.
public const string hsi_select_copilot_down = "sim/autopilot/hsi_select_copilot_down";           //HSI select down one, copilot.
public const string hsi_select_copilot_up = "sim/autopilot/hsi_select_copilot_up";           //HSI select up one, copilot.
public const string hsi_select_copilot_nav_1 = "sim/autopilot/hsi_select_copilot_nav_1";           //HSI shows NAV 1, copilot.
public const string hsi_select_copilot_nav_2 = "sim/autopilot/hsi_select_copilot_nav_2";           //HSI shows NAV 2, copilot.
public const string hsi_select_copilot_gps = "sim/autopilot/hsi_select_copilot_gps";           //HSI shows GPS, copilot.
public const string source_01 = "sim/autopilot/source_01";           //Autopilot pitot static source, 0 or 1
public const string fdir_on = "sim/autopilot/fdir_on";           //Flight director on.
public const string fdir_toggle = "sim/autopilot/fdir_toggle";           //Flight director toggle.
public const string servos_on = "sim/autopilot/servos_on";           //Servos on.
public const string servos_toggle = "sim/autopilot/servos_toggle";           //Servos toggle.
public const string fdir_servos_down_one = "sim/autopilot/fdir_servos_down_one";           //Flight director down (on/FDIR/off).
public const string fdir_servos_up_one = "sim/autopilot/fdir_servos_up_one";           //Flight director up (off/FDIR/on).
public const string servos_fdir_off = "sim/autopilot/servos_fdir_off";           //Disco servos, flt dir.
public const string servos_fdir_yawd_off = "sim/autopilot/servos_fdir_yawd_off";           //Disco servos, flt dir, yaw damp.
public const string servos_fdir_yawd_trim_off = "sim/autopilot/servos_fdir_yawd_trim_off";           //Disco servos, flt dir, yaw damp, trim.
public const string control_wheel_steer = "sim/autopilot/control_wheel_steer";           //Control wheel steering mode.
public const string autothrottle_on = "sim/autopilot/autothrottle_on";           //Autopilot auto-throttle on.
public const string autothrottle_off = "sim/autopilot/autothrottle_off";           //Autopilot auto-throttle off.
public const string autothrottle_toggle = "sim/autopilot/autothrottle_toggle";           //Autopilot auto-throttle toggle.
public const string heading = "sim/autopilot/heading";           //Autopilot heading-hold.
public const string wing_leveler = "sim/autopilot/wing_leveler";           //Autopilot wing-level.
public const string NAV = "sim/autopilot/NAV";           //Autopilot VOR/LOC arm.
public const string vertical_speed = "sim/autopilot/vertical_speed";           //Autopilot vertical speed, at current VSI.
public const string vertical_speed_pre_sel = "sim/autopilot/vertical_speed_pre_sel";           //Autopilot vertical speed, at pre-sel VSI.
public const string pitch_sync = "sim/autopilot/pitch_sync";           //Autopilot pitch-sync.
public const string level_change = "sim/autopilot/level_change";           //Autopilot level change.
public const string altitude_hold = "sim/autopilot/altitude_hold";           //Autopilot altitude select or hold.
public const string terrain_following = "sim/autopilot/terrain_following";           //Autopilot terrain-mode following.
public const string take_off_go_around = "sim/autopilot/take_off_go_around";           //Autopilot take-off go-around.
public const string reentry = "sim/autopilot/reentry";           //Autopilot re-entry.
public const string glide_slope = "sim/autopilot/glide_slope";           //Autopilot glideslope.
public const string vnav = "sim/autopilot/vnav";           //Autopilot VNAV for G1000.
public const string airspeed_sync = "sim/autopilot/airspeed_sync";           //Autopilot airspeed sync.
public const string heading_sync = "sim/autopilot/heading_sync";           //Autopilot heading sync.
public const string vertical_speed_sync = "sim/autopilot/vertical_speed_sync";           //Autopilot VVI sync.
public const string altitude_sync = "sim/autopilot/altitude_sync";           //Autopilot altitude sync.
public const string heading_down = "sim/autopilot/heading_down";           //Autopilot heading down.
public const string heading_up = "sim/autopilot/heading_up";           //Autopilot heading up.
public const string heading_copilot_down = "sim/autopilot/heading_copilot_down";           //Autopilot heading copilot down.
public const string heading_copilot_up = "sim/autopilot/heading_copilot_up";           //Autopilot heading copilot up.
public const string airspeed_down = "sim/autopilot/airspeed_down";           //Autopilot airspeed down.
public const string airspeed_up = "sim/autopilot/airspeed_up";           //Autopilot airspeed up.
public const string vertical_speed_down = "sim/autopilot/vertical_speed_down";           //Autopilot VVI down.
public const string vertical_speed_up = "sim/autopilot/vertical_speed_up";           //Autopilot VVI up.
public const string altitude_down = "sim/autopilot/altitude_down";           //Autopilot altitude down.
public const string altitude_up = "sim/autopilot/altitude_up";           //Autopilot altitude up.
public const string nose_down = "sim/autopilot/nose_down";           //Autopilot nose down.
public const string nose_up = "sim/autopilot/nose_up";           //Autopilot nose up.
public const string nose_down_pitch_mode = "sim/autopilot/nose_down_pitch_mode";           //Autopilot nose down, go into pitch mode.
public const string nose_up_pitch_mode = "sim/autopilot/nose_up_pitch_mode";           //Autopilot nose up, go into pitch mode
public const string override_left = "sim/autopilot/override_left";           //Autopilot override left: Go to ROL mode.
public const string override_right = "sim/autopilot/override_right";           //Autopilot override right: Go to ROL mode.
public const string override_up = "sim/autopilot/override_up";           //Autopilot override up: Go to SYN mode.
public const string override_down = "sim/autopilot/override_down";           //Autopilot override down: Go to SYN mode.
public const string altitude_arm = "sim/autopilot/altitude_arm";           //Autopilot altitude hold ARM.
public const string approach = "sim/autopilot/approach";           //Autopilot approach.
public const string back_course = "sim/autopilot/back_course";           //Autopilot back-course.
public const string knots_mach_toggle = "sim/autopilot/knots_mach_toggle";           //Toggle knots-Mach airspeeed hold.
public const string FMS = "sim/autopilot/FMS";           //Autopilot FMS altitude.
public const string bank_limit_down = "sim/autopilot/bank_limit_down";           //Bank angle limit down.
public const string bank_limit_up = "sim/autopilot/bank_limit_up";           //Bank angle limit up.
public const string bank_limit_toggle = "sim/autopilot/bank_limit_toggle";           //Bank angle limit toggle.
public const string soft_ride_toggle = "sim/autopilot/soft_ride_toggle";           //Soft ride toggle.
public const string test_auto_annunciators = "sim/autopilot/test_auto_annunciators";           //Autopilot test annunciators.
public const string set_ott_seldisp_ALT_VVI_vvi = "sim/autopilot/set_ott_seldisp_ALT_VVI_vvi";           //Let ott_seldisp_ALT_VVI show VVI.
public const string set_ott_seldisp_ALT_VVI_alt = "sim/autopilot/set_ott_seldisp_ALT_VVI_alt";           //Let ott_seldisp_ALT_VVI show ALT.