public const string bleed_air_down = "sim/bleed_air/bleed_air_down";      //Bleed air mode down.
public const string bleed_air_up = "sim/bleed_air/bleed_air_up";      //Bleed air mode up.
public const string bleed_air_off = "sim/bleed_air/bleed_air_off";      //Bleed air off.
public const string bleed_air_left = "sim/bleed_air/bleed_air_left";      //Bleed air from left engine.
public const string bleed_air_both = "sim/bleed_air/bleed_air_both";      //Bleed air from either engine.
public const string bleed_air_right = "sim/bleed_air/bleed_air_right";      //Bleed air from right engine.
public const string bleed_air_apu = "sim/bleed_air/bleed_air_apu";      //Bleed air from APU.
public const string bleed_air_auto = "sim/bleed_air/bleed_air_auto";      //Bleed air from any engine or APU.
public const string bleed_air_left_on = "sim/bleed_air/bleed_air_left_on";      //Bleed air left engine on.
public const string bleed_air_left_ins_only = "sim/bleed_air/bleed_air_left_ins_only";      //Bleed air left engine instruments only.
public const string bleed_air_left_off = "sim/bleed_air/bleed_air_left_off";      //Bleed air left engine off.
public const string bleed_air_right_on = "sim/bleed_air/bleed_air_right_on";      //Bleed air right engine on.
public const string bleed_air_right_ins_only = "sim/bleed_air/bleed_air_right_ins_only";      //Bleed air right engine instruments only.
public const string bleed_air_right_off = "sim/bleed_air/bleed_air_right_off";      //Bleed air right engine off.