public const string cross_tie_on = "sim/electrical/cross_tie_on";                        //Cross-tie on.
public const string cross_tie_off = "sim/electrical/cross_tie_off";                       //Cross-tie off.
public const string cross_tie_toggle = "sim/electrical/cross_tie_toggle";                    //Cross-tie toggle.
public const string inverters_on = "sim/electrical/inverters_on";                        //Inverters on.
public const string inverters_off = "sim/electrical/inverters_off";                       //Inverters off.
public const string inverters_toggle = "sim/electrical/inverters_toggle";                    //Inverters toggle.
public const string inverter_1_on = "sim/electrical/inverter_1_on";                       //Inverter 1 on.
public const string inverter_1_off = "sim/electrical/inverter_1_off";                      //Inverter 1 off.
public const string inverter_1_toggle = "sim/electrical/inverter_1_toggle";                   //Inverter 1 toggle.
public const string inverter_2_on = "sim/electrical/inverter_2_on";                       //Inverter 2 on.
public const string inverter_2_off = "sim/electrical/inverter_2_off";                      //Inverter 2 off.
public const string inverter_2_toggle = "sim/electrical/inverter_2_toggle";                   //Inverter 2 toggle.
public const string batteries_toggle = "sim/electrical/batteries_toggle";                    //Batteries all toggle.
public const string battery_1_on = "sim/electrical/battery_1_on";                        //Battery 1 on.
public const string battery_2_on = "sim/electrical/battery_2_on";                        //Battery 2 on.
public const string battery_1_off = "sim/electrical/battery_1_off";                       //Battery 1 off.
public const string battery_2_off = "sim/electrical/battery_2_off";                       //Battery 2 off.
public const string battery_1_toggle = "sim/electrical/battery_1_toggle";                    //Battery 1 toggle.
public const string battery_2_toggle = "sim/electrical/battery_2_toggle";                    //Battery 2 toggle.
public const string generators_toggle = "sim/electrical/generators_toggle";                   //Generators all toggle.
public const string generator_1_off = "sim/electrical/generator_1_off";                     //Generator #1 off.
public const string generator_2_off = "sim/electrical/generator_2_off";                     //Generator #2 off.
public const string generator_3_off = "sim/electrical/generator_3_off";                     //Generator #3 off.
public const string generator_4_off = "sim/electrical/generator_4_off";                     //Generator #4 off.
public const string generator_5_off = "sim/electrical/generator_5_off";                     //Generator #5 off.
public const string generator_6_off = "sim/electrical/generator_6_off";                     //Generator #6 off.
public const string generator_7_off = "sim/electrical/generator_7_off";                     //Generator #7 off.
public const string generator_8_off = "sim/electrical/generator_8_off";                     //Generator #8 off.
public const string generator_1_on = "sim/electrical/generator_1_on";                      //Generator #1 on.
public const string generator_2_on = "sim/electrical/generator_2_on";                      //Generator #2 on.
public const string generator_3_on = "sim/electrical/generator_3_on";                      //Generator #3 on.
public const string generator_4_on = "sim/electrical/generator_4_on";                      //Generator #4 on.
public const string generator_5_on = "sim/electrical/generator_5_on";                      //Generator #5 on.
public const string generator_6_on = "sim/electrical/generator_6_on";                      //Generator #6 on.
public const string generator_7_on = "sim/electrical/generator_7_on";                      //Generator #7 on.
public const string generator_8_on = "sim/electrical/generator_8_on";                      //Generator #8 on.
public const string generator_1_toggle = "sim/electrical/generator_1_toggle";                  //Generator #1 toggle.
public const string generator_2_toggle = "sim/electrical/generator_2_toggle";                  //Generator #2 toggle.
public const string generator_3_toggle = "sim/electrical/generator_3_toggle";                  //Generator #3 toggle.
public const string generator_4_toggle = "sim/electrical/generator_4_toggle";                  //Generator #4 toggle.
public const string generator_5_toggle = "sim/electrical/generator_5_toggle";                  //Generator #5 toggle.
public const string generator_6_toggle = "sim/electrical/generator_6_toggle";                  //Generator #6 toggle.
public const string generator_7_toggle = "sim/electrical/generator_7_toggle";                  //Generator #7 toggle.
public const string generator_8_toggle = "sim/electrical/generator_8_toggle";                  //Generator #8 toggle.
public const string generator_1_reset = "sim/electrical/generator_1_reset";                   //Generator #1 reset.
public const string generator_2_reset = "sim/electrical/generator_2_reset";                   //Generator #2 reset.
public const string generator_3_reset = "sim/electrical/generator_3_reset";                   //Generator #3 reset.
public const string generator_4_reset = "sim/electrical/generator_4_reset";                   //Generator #4 reset.
public const string generator_5_reset = "sim/electrical/generator_5_reset";                   //Generator #5 reset.
public const string generator_6_reset = "sim/electrical/generator_6_reset";                   //Generator #6 reset.
public const string generator_7_reset = "sim/electrical/generator_7_reset";                   //Generator #7 reset.
public const string generator_8_reset = "sim/electrical/generator_8_reset";                   //Generator #8 reset.
public const string APU_start = "sim/electrical/APU_start";                           //APU start.
public const string APU_on = "sim/electrical/APU_on";                              //APU on.
public const string APU_off = "sim/electrical/APU_off";                             //APU off.
public const string APU_generator_on = "sim/electrical/APU_generator_on";                    //APU generator on.
public const string APU_generator_off = "sim/electrical/APU_generator_off";                   //APU generator off.
public const string GPU_on = "sim/electrical/GPU_on";                              //GPU on.
public const string GPU_off = "sim/electrical/GPU_off";                             //GPU off.
public const string GPU_toggle = "sim/electrical/GPU_toggle";                          //GPU toggle.
public const string dc_volt_dn = "sim/electrical/dc_volt_dn";           //DC Voltmeter down.
public const string dc_volt_up = "sim/electrical/dc_volt_up";           //DC Voltmeter up.
public const string dc_volt_ext = "sim/electrical/dc_volt_ext";           //DC Voltmeter external power.
public const string dc_volt_ctr = "sim/electrical/dc_volt_ctr";           //DC Voltmeter center.
public const string dc_volt_lft = "sim/electrical/dc_volt_lft";           //DC Voltmeter left.
public const string dc_volt_rgt = "sim/electrical/dc_volt_rgt";           //DC Voltmeter right.
public const string dc_volt_tpl = "sim/electrical/dc_volt_tpl";           //DC Voltmeter TPL-fed.
public const string dc_volt_bat = "sim/electrical/dc_volt_bat";           //DC Voltmeter battery.