public const string engage_starters = "sim/engines/engage_starters";                        //Engage starters.
public const string throttle_down = "sim/engines/throttle_down";                          //Throttle down a bit.
public const string throttle_up = "sim/engines/throttle_up";                            //Throttle up a bit.
public const string TOGA_power = "sim/engines/TOGA_power";                             //Engage TOGA power.
public const string prop_down = "sim/engines/prop_down";                              //Prop coarse a bit.
public const string prop_up = "sim/engines/prop_up";                                //Prop fine a bit.
public const string mixture_min = "sim/engines/mixture_min";                            //Mixture to cut off.
public const string mixture_down = "sim/engines/mixture_down";                           //Mixture lean a bit.
public const string mixture_up = "sim/engines/mixture_up";                             //Mixture rich a bit.
public const string mixture_max = "sim/engines/mixture_max";                            //Mixture to full rich.
public const string carb_heat_off = "sim/engines/carb_heat_off";                          //Carb heat off.
public const string carb_heat_on = "sim/engines/carb_heat_on";                           //Carb heat on.
public const string carb_heat_toggle = "sim/engines/carb_heat_toggle";                       //Carb heat toggle.
public const string idle_hi_lo_toggle = "sim/engines/idle_hi_lo_toggle";                      //Idle high/low toggle.
public const string governor_on = "sim/engines/governor_on";                            //Throttle governor on.
public const string governor_off = "sim/engines/governor_off";                           //Throttle governor off.
public const string governor_toggle = "sim/engines/governor_toggle";                        //Throttle governor toggle.
public const string clutch_on = "sim/engines/clutch_on";                              //Clutch on.
public const string clutch_off = "sim/engines/clutch_off";                             //Clutch off.
public const string clutch_toggle = "sim/engines/clutch_toggle";                          //Clutch toggle.
public const string beta_toggle = "sim/engines/beta_toggle";                            //Toggle Beta prop.
public const string thrust_reverse_toggle = "sim/engines/thrust_reverse_toggle";                  //Toggle thrust reversers.
public const string thrust_reverse_hold = "sim/engines/thrust_reverse_hold";                    //Hold thrust reverse at max.
public const string throttle_down_1 = "sim/engines/throttle_down_1";                        //Throttle down a bit for engine #1.
public const string throttle_down_2 = "sim/engines/throttle_down_2";                        //Throttle down a bit for engine #2.
public const string throttle_down_3 = "sim/engines/throttle_down_3";                        //Throttle down a bit for engine #3.
public const string throttle_down_4 = "sim/engines/throttle_down_4";                        //Throttle down a bit for engine #4.
public const string throttle_down_5 = "sim/engines/throttle_down_5";                        //Throttle down a bit for engine #5.
public const string throttle_down_6 = "sim/engines/throttle_down_6";                        //Throttle down a bit for engine #6.
public const string throttle_down_7 = "sim/engines/throttle_down_7";                        //Throttle down a bit for engine #7.
public const string throttle_down_8 = "sim/engines/throttle_down_8";                        //Throttle down a bit for engine #8.
public const string throttle_up_1 = "sim/engines/throttle_up_1";                          //Throttle up a bit for engine #1.
public const string throttle_up_2 = "sim/engines/throttle_up_2";                          //Throttle up a bit for engine #2.
public const string throttle_up_3 = "sim/engines/throttle_up_3";                          //Throttle up a bit for engine #3.
public const string throttle_up_4 = "sim/engines/throttle_up_4";                          //Throttle up a bit for engine #4.
public const string throttle_up_5 = "sim/engines/throttle_up_5";                          //Throttle up a bit for engine #5.
public const string throttle_up_6 = "sim/engines/throttle_up_6";                          //Throttle up a bit for engine #6.
public const string throttle_up_7 = "sim/engines/throttle_up_7";                          //Throttle up a bit for engine #7.
public const string throttle_up_8 = "sim/engines/throttle_up_8";                          //Throttle up a bit for engine #8.
public const string prop_down_1 = "sim/engines/prop_down_1";                            //Prop down a bit for engine #1.
public const string prop_down_2 = "sim/engines/prop_down_2";                            //Prop down a bit for engine #2.
public const string prop_down_3 = "sim/engines/prop_down_3";                            //Prop down a bit for engine #3.
public const string prop_down_4 = "sim/engines/prop_down_4";                            //Prop down a bit for engine #4.
public const string prop_down_5 = "sim/engines/prop_down_5";                            //Prop down a bit for engine #5.
public const string prop_down_6 = "sim/engines/prop_down_6";                            //Prop down a bit for engine #6.
public const string prop_down_7 = "sim/engines/prop_down_7";                            //Prop down a bit for engine #7.
public const string prop_down_8 = "sim/engines/prop_down_8";                            //Prop down a bit for engine #8.
public const string prop_up_1 = "sim/engines/prop_up_1";                              //Prop up a bit for engine #1.
public const string prop_up_2 = "sim/engines/prop_up_2";                              //Prop up a bit for engine #2.
public const string prop_up_3 = "sim/engines/prop_up_3";                              //Prop up a bit for engine #3.
public const string prop_up_4 = "sim/engines/prop_up_4";                              //Prop up a bit for engine #4.
public const string prop_up_5 = "sim/engines/prop_up_5";                              //Prop up a bit for engine #5.
public const string prop_up_6 = "sim/engines/prop_up_6";                              //Prop up a bit for engine #6.
public const string prop_up_7 = "sim/engines/prop_up_7";                              //Prop up a bit for engine #7.
public const string prop_up_8 = "sim/engines/prop_up_8";                              //Prop up a bit for engine #8.
public const string mixture_down_1 = "sim/engines/mixture_down_1";                         //Mixture down a bit for engine #1.
public const string mixture_down_2 = "sim/engines/mixture_down_2";                         //Mixture down a bit for engine #2.
public const string mixture_down_3 = "sim/engines/mixture_down_3";                         //Mixture down a bit for engine #3.
public const string mixture_down_4 = "sim/engines/mixture_down_4";                         //Mixture down a bit for engine #4.
public const string mixture_down_5 = "sim/engines/mixture_down_5";                         //Mixture down a bit for engine #5.
public const string mixture_down_6 = "sim/engines/mixture_down_6";                         //Mixture down a bit for engine #6.
public const string mixture_down_7 = "sim/engines/mixture_down_7";                         //Mixture down a bit for engine #7.
public const string mixture_down_8 = "sim/engines/mixture_down_8";                         //Mixture down a bit for engine #8.
public const string mixture_up_1 = "sim/engines/mixture_up_1";                           //Mixture up a bit for engine #1.
public const string mixture_up_2 = "sim/engines/mixture_up_2";                           //Mixture up a bit for engine #2.
public const string mixture_up_3 = "sim/engines/mixture_up_3";                           //Mixture up a bit for engine #3.
public const string mixture_up_4 = "sim/engines/mixture_up_4";                           //Mixture up a bit for engine #4.
public const string mixture_up_5 = "sim/engines/mixture_up_5";                           //Mixture up a bit for engine #5.
public const string mixture_up_6 = "sim/engines/mixture_up_6";                           //Mixture up a bit for engine #6.
public const string mixture_up_7 = "sim/engines/mixture_up_7";                           //Mixture up a bit for engine #7.
public const string mixture_up_8 = "sim/engines/mixture_up_8";                           //Mixture up a bit for engine #8.
public const string beta_toggle_1 = "sim/engines/beta_toggle_1";                          //Toggle beta prop #1.
public const string beta_toggle_2 = "sim/engines/beta_toggle_2";                          //Toggle beta prop #2.
public const string beta_toggle_3 = "sim/engines/beta_toggle_3";                          //Toggle beta prop #3.
public const string beta_toggle_4 = "sim/engines/beta_toggle_4";                          //Toggle beta prop #4.
public const string beta_toggle_5 = "sim/engines/beta_toggle_5";                          //Toggle beta prop #5.
public const string beta_toggle_6 = "sim/engines/beta_toggle_6";                          //Toggle beta prop #6.
public const string beta_toggle_7 = "sim/engines/beta_toggle_7";                          //Toggle beta prop #7.
public const string beta_toggle_8 = "sim/engines/beta_toggle_8";                          //Toggle beta prop #8.
public const string thrust_reverse_toggle_1 = "sim/engines/thrust_reverse_toggle_1";                //Toggle thrust reversers #1.
public const string thrust_reverse_toggle_2 = "sim/engines/thrust_reverse_toggle_2";                //Toggle thrust reversers #2.
public const string thrust_reverse_toggle_3 = "sim/engines/thrust_reverse_toggle_3";                //Toggle thrust reversers #3.
public const string thrust_reverse_toggle_4 = "sim/engines/thrust_reverse_toggle_4";                //Toggle thrust reversers #4.
public const string thrust_reverse_toggle_5 = "sim/engines/thrust_reverse_toggle_5";                //Toggle thrust reversers #5.
public const string thrust_reverse_toggle_6 = "sim/engines/thrust_reverse_toggle_6";                //Toggle thrust reversers #6.
public const string thrust_reverse_toggle_7 = "sim/engines/thrust_reverse_toggle_7";                //Toggle thrust reversers #7.
public const string thrust_reverse_toggle_8 = "sim/engines/thrust_reverse_toggle_8";                //Toggle thrust reversers #8.
public const string thrust_reverse_hold_1 = "sim/engines/thrust_reverse_hold_1";                  //Hold thrust reverse at max #1.
public const string thrust_reverse_hold_2 = "sim/engines/thrust_reverse_hold_2";                  //Hold thrust reverse at max #2.
public const string thrust_reverse_hold_3 = "sim/engines/thrust_reverse_hold_3";                  //Hold thrust reverse at max #3.
public const string thrust_reverse_hold_4 = "sim/engines/thrust_reverse_hold_4";                  //Hold thrust reverse at max #4.
public const string thrust_reverse_hold_5 = "sim/engines/thrust_reverse_hold_5";                  //Hold thrust reverse at max #5.
public const string thrust_reverse_hold_6 = "sim/engines/thrust_reverse_hold_6";                  //Hold thrust reverse at max #6.
public const string thrust_reverse_hold_7 = "sim/engines/thrust_reverse_hold_7";                  //Hold thrust reverse at max #7.
public const string thrust_reverse_hold_8 = "sim/engines/thrust_reverse_hold_8";                  //Hold thrust reverse at max #8.
public const string fire_ext_1_off = "sim/engines/fire_ext_1_off";                         //Fire extinguisher #1 off.
public const string fire_ext_2_off = "sim/engines/fire_ext_2_off";                         //Fire extinguisher #2 off.
public const string fire_ext_3_off = "sim/engines/fire_ext_3_off";                         //Fire extinguisher #3 off.
public const string fire_ext_4_off = "sim/engines/fire_ext_4_off";                         //Fire extinguisher #4 off.
public const string fire_ext_5_off = "sim/engines/fire_ext_5_off";                         //Fire extinguisher #5 off.
public const string fire_ext_6_off = "sim/engines/fire_ext_6_off";                         //Fire extinguisher #6 off.
public const string fire_ext_7_off = "sim/engines/fire_ext_7_off";                         //Fire extinguisher #7 off.
public const string fire_ext_8_off = "sim/engines/fire_ext_8_off";                         //Fire extinguisher #8 off.
public const string fire_ext_1_on = "sim/engines/fire_ext_1_on";                          //Fire extinguisher #1 on.
public const string fire_ext_2_on = "sim/engines/fire_ext_2_on";                          //Fire extinguisher #2 on.
public const string fire_ext_3_on = "sim/engines/fire_ext_3_on";                          //Fire extinguisher #3 on.
public const string fire_ext_4_on = "sim/engines/fire_ext_4_on";                          //Fire extinguisher #4 on.
public const string fire_ext_5_on = "sim/engines/fire_ext_5_on";                          //Fire extinguisher #5 on.
public const string fire_ext_6_on = "sim/engines/fire_ext_6_on";                          //Fire extinguisher #6 on.
public const string fire_ext_7_on = "sim/engines/fire_ext_7_on";                          //Fire extinguisher #7 on.
public const string fire_ext_8_on = "sim/engines/fire_ext_8_on";                          //Fire extinguisher #8 on.
public const string rockets_up = "sim/engines/rockets_up";                             //Orbital maneuver rockets up.
public const string rockets_down = "sim/engines/rockets_down";                           //Orbital maneuver rockets down.
public const string rockets_left = "sim/engines/rockets_left";                           //Orbital maneuver rockets left.
public const string rockets_right = "sim/engines/rockets_right";                          //Orbital maneuver rockets right.
public const string rockets_forward = "sim/engines/rockets_forward";                        //Orbital maneuver rockets fore.
public const string rockets_aft = "sim/engines/rockets_aft";                            //Orbital maneuver rockets aft.