public const string fadec_toggle = "sim/fadec/fadec_toggle";                             //FADEC toggle.
public const string fadec_1_off = "sim/fadec/fadec_1_off";                              //FADEC #1 off.
public const string fadec_2_off = "sim/fadec/fadec_2_off";                              //FADEC #2 off.
public const string fadec_3_off = "sim/fadec/fadec_3_off";                              //FADEC #3 off.
public const string fadec_4_off = "sim/fadec/fadec_4_off";                              //FADEC #4 off.
public const string fadec_5_off = "sim/fadec/fadec_5_off";                              //FADEC #5 off.
public const string fadec_6_off = "sim/fadec/fadec_6_off";                              //FADEC #6 off.
public const string fadec_7_off = "sim/fadec/fadec_7_off";                              //FADEC #7 off.
public const string fadec_8_off = "sim/fadec/fadec_8_off";                              //FADEC #8 off.
public const string fadec_1_on = "sim/fadec/fadec_1_on";                               //FADEC #1 on.
public const string fadec_2_on = "sim/fadec/fadec_2_on";                               //FADEC #2 on.
public const string fadec_3_on = "sim/fadec/fadec_3_on";                               //FADEC #3 on.
public const string fadec_4_on = "sim/fadec/fadec_4_on";                               //FADEC #4 on.
public const string fadec_5_on = "sim/fadec/fadec_5_on";                               //FADEC #5 on.
public const string fadec_6_on = "sim/fadec/fadec_6_on";                               //FADEC #6 on.
public const string fadec_7_on = "sim/fadec/fadec_7_on";                               //FADEC #7 on.
public const string fadec_8_on = "sim/fadec/fadec_8_on";                               //FADEC #8 on.