public const string cowl_flaps_open = "sim/flight_controls/cowl_flaps_open";                //Move cowl flaps open a bit.
public const string cowl_flaps_closed = "sim/flight_controls/cowl_flaps_closed";              //Move cowl flaps to closed a bit.
public const string cowl_flaps_closed_1 = "sim/flight_controls/cowl_flaps_closed_1";            //Move cowl flaps #1 closed a bit.
public const string cowl_flaps_closed_2 = "sim/flight_controls/cowl_flaps_closed_2";            //Move cowl flaps #2 closed a bit.
public const string cowl_flaps_closed_3 = "sim/flight_controls/cowl_flaps_closed_3";            //Move cowl flaps #3 closed a bit.
public const string cowl_flaps_closed_4 = "sim/flight_controls/cowl_flaps_closed_4";            //Move cowl flaps #4 closed a bit.
public const string cowl_flaps_closed_5 = "sim/flight_controls/cowl_flaps_closed_5";            //Move cowl flaps #5 closed a bit.
public const string cowl_flaps_closed_6 = "sim/flight_controls/cowl_flaps_closed_6";            //Move cowl flaps #6 closed a bit.
public const string cowl_flaps_closed_7 = "sim/flight_controls/cowl_flaps_closed_7";            //Move cowl flaps #7 closed a bit.
public const string cowl_flaps_closed_8 = "sim/flight_controls/cowl_flaps_closed_8";            //Move cowl flaps #8 closed a bit.
public const string cowl_flaps_open_1 = "sim/flight_controls/cowl_flaps_open_1";              //Move cowl flaps #1 open a bit.
public const string cowl_flaps_open_2 = "sim/flight_controls/cowl_flaps_open_2";              //Move cowl flaps #2 open a bit.
public const string cowl_flaps_open_3 = "sim/flight_controls/cowl_flaps_open_3";              //Move cowl flaps #3 open a bit.
public const string cowl_flaps_open_4 = "sim/flight_controls/cowl_flaps_open_4";              //Move cowl flaps #4 open a bit.
public const string cowl_flaps_open_5 = "sim/flight_controls/cowl_flaps_open_5";              //Move cowl flaps #5 open a bit.
public const string cowl_flaps_open_6 = "sim/flight_controls/cowl_flaps_open_6";              //Move cowl flaps #6 open a bit.
public const string cowl_flaps_open_7 = "sim/flight_controls/cowl_flaps_open_7";              //Move cowl flaps #7 open a bit.
public const string cowl_flaps_open_8 = "sim/flight_controls/cowl_flaps_open_8";              //Move cowl flaps #8 open a bit.
public const string flaps_up = "sim/flight_controls/flaps_up";                       //Flaps up a notch.
public const string flaps_down = "sim/flight_controls/flaps_down";                     //Flaps down a notch.
public const string vector_sweep_aft = "sim/flight_controls/vector_sweep_aft";               //Vector or sweep aft.
public const string vector_sweep_forward = "sim/flight_controls/vector_sweep_forward";           //Vector or sweep forward.
public const string blimp_lift_down = "sim/flight_controls/blimp_lift_down";                //Blimp lift down a bit.
public const string blimp_lift_up = "sim/flight_controls/blimp_lift_up";                  //Blimp lift up a bit.
public const string speed_brakes_down_one = "sim/flight_controls/speed_brakes_down_one";          //Speedbrakes extend one.
public const string speed_brakes_up_one = "sim/flight_controls/speed_brakes_up_one";            //Speedbrakes retract one.
public const string speed_brakes_down_all = "sim/flight_controls/speed_brakes_down_all";          //Speedbrakes extend full.
public const string speed_brakes_up_all = "sim/flight_controls/speed_brakes_up_all";            //Speedbrakes retract full.
public const string speed_brakes_toggle = "sim/flight_controls/speed_brakes_toggle";            //Speedbrakes toggle.
public const string landing_gear_down = "sim/flight_controls/landing_gear_down";              //Landing gear down.
public const string landing_gear_up = "sim/flight_controls/landing_gear_up";                //Landing gear up.
public const string landing_gear_toggle = "sim/flight_controls/landing_gear_toggle";            //Landing gear toggle.
public const string landing_gear_emer_on = "sim/flight_controls/landing_gear_emer_on";           //Landing gear emergency override down.
public const string landing_gear_emer_off = "sim/flight_controls/landing_gear_emer_off";          //Landing gear emergency override off.
public const string nwheel_steer_toggle = "sim/flight_controls/nwheel_steer_toggle";            //Nosewheel steer toggle.
public const string tail_wheel_lock_toggle = "sim/flight_controls/tail_wheel_lock_toggle";         //Toggle tailwheel lock.
public const string tail_wheel_lock_engage = "sim/flight_controls/tail_wheel_lock_engage";         //Engage tailwheel lock.
public const string brakes_toggle_regular = "sim/flight_controls/brakes_toggle_regular";          //Toggle brakes regular effort.
public const string brakes_toggle_max = "sim/flight_controls/brakes_toggle_max";              //Toggle brakes max effort.
public const string brakes_regular = "sim/flight_controls/brakes_regular";                 //Hold brakes regular.
public const string brakes_max = "sim/flight_controls/brakes_max";                     //Hold brakes maximum.
public const string brakes_toggle_auto = "sim/flight_controls/brakes_toggle_auto";             //Toggle auto-brakes.
public const string brakes_dn_auto = "sim/flight_controls/brakes_dn_auto";                 //Auto-brakes down.
public const string brakes_up_auto = "sim/flight_controls/brakes_up_auto";                 //Auto-brakes up.
public const string hydraulic_on = "sim/flight_controls/hydraulic_on";                   //Engine-driven hydraulic pumps on
public const string hydraulic_off = "sim/flight_controls/hydraulic_off";                  //Engine-driven hydraulic pumps off
public const string hydraulic_tog = "sim/flight_controls/hydraulic_tog";                  //Engine-driven hydraulic pumps tog
public const string tailhook_down = "sim/flight_controls/tailhook_down";                  //Tailhook down.
public const string tailhook_up = "sim/flight_controls/tailhook_up";                    //Tailhook up.
public const string tailhook_toggle = "sim/flight_controls/tailhook_toggle";                //Toggle the tailhook.
public const string canopy_open = "sim/flight_controls/canopy_open";                    //Canopy open.
public const string canopy_close = "sim/flight_controls/canopy_close";                   //Canopy close.
public const string canopy_toggle = "sim/flight_controls/canopy_toggle";                  //Canopy toggle.
public const string rotor_brake_toggle = "sim/flight_controls/rotor_brake_toggle";             //Toggle rotor brake.
public const string puffers_toggle = "rsim/flight_controls/puffers_toggle";                 //Toggle puffers.
public const string parachute_flares = "sim/flight_controls/parachute_flares";      //Deploy parachute flares.
public const string smoke_toggle = "sim/flight_controls/smoke_toggle";      //Toggle smoke puffing.
public const string water_scoop_toggle = "sim/flight_controls/water_scoop_toggle";      //Toggle water scoop.
public const string boost = "sim/flight_controls/boost";      //Water or Nitrous engine BOOST.
public const string ignite_jato = "sim/flight_controls/ignite_jato";      //Ignite JATO.
public const string jettison_payload = "sim/flight_controls/jettison_payload";      //Jettison the payload.
public const string dump_fuel_toggle = "sim/flight_controls/dump_fuel_toggle";      //Dump fuel.
public const string deploy_parachute = "sim/flight_controls/deploy_parachute";      //Deploy/jettison chute.
public const string eject = "sim/flight_controls/eject";      //Eject.
public const string drop_tank = "sim/flight_controls/drop_tank";      //Drop all drop tanks.
public const string door_open_1 = "sim/flight_controls/door_open_1";           //Door #1 open.
public const string door_open_2 = "sim/flight_controls/door_open_2";           //Door #2 open.
public const string door_open_3 = "sim/flight_controls/door_open_3";           //Door #3 open.
public const string door_open_4 = "sim/flight_controls/door_open_4";           //Door #4 open.
public const string door_open_5 = "sim/flight_controls/door_open_5";           //Door #5 open.
public const string door_open_6 = "sim/flight_controls/door_open_6";           //Door #6 open.
public const string door_open_7 = "sim/flight_controls/door_open_7";           //Door #7 open.
public const string door_open_8 = "sim/flight_controls/door_open_8";           //Door #8 open.
public const string door_open_9 = "sim/flight_controls/door_open_9";           //Door #9 open.
public const string door_open_10 = "sim/flight_controls/door_open_10";           //Door #10 open.
public const string door_close_1 = "sim/flight_controls/door_close_1";           //Door #1 close.
public const string door_close_2 = "sim/flight_controls/door_close_2";           //Door #2 close.
public const string door_close_3 = "sim/flight_controls/door_close_3";           //Door #3 close.
public const string door_close_4 = "sim/flight_controls/door_close_4";           //Door #4 close.
public const string door_close_5 = "sim/flight_controls/door_close_5";           //Door #5 close.
public const string door_close_6 = "sim/flight_controls/door_close_6";           //Door #6 close.
public const string door_close_7 = "sim/flight_controls/door_close_7";           //Door #7 close.
public const string door_close_8 = "sim/flight_controls/door_close_8";           //Door #8 close.
public const string door_close_9 = "sim/flight_controls/door_close_9";           //Door #9 close.
public const string door_close_10 = "sim/flight_controls/door_close_10";           //Door #10 close.
public const string glider_tow_release = "sim/flight_controls/glider_tow_release";           //Release tow-plane cable for gliders.
public const string winch_release = "sim/flight_controls/winch_release";           //Release winch (for gliders).
public const string glider_all_release = "sim/flight_controls/glider_all_release";           //Release tow-plane and winch for gliders.
public const string engage_cat_shot = "sim/flight_controls/engage_cat_shot";           //Engage catapault.
public const string glider_tow_left = "sim/flight_controls/glider_tow_left";           //Tow-plane for gliders: Take me left.
public const string glider_tow_straight = "sim/flight_controls/glider_tow_straight";           //Tow-plane for gliders: Take me straight.
public const string glider_tow_right = "sim/flight_controls/glider_tow_right";           //Tow-plane for gliders: Take me right.
public const string carrier_ILS = "sim/flight_controls/carrier_ILS";           //Set the radios for the carrier ILS.
public const string pump_flaps = "sim/flight_controls/pump_flaps";           //Pump flaps up/down.
public const string pump_gear = "sim/flight_controls/pump_gear";           //Pump gear up/down.
public const string pitch_trim_up = "sim/flight_controls/pitch_trim_up";           //Pitch trim up.
public const string pitch_trim_down = "sim/flight_controls/pitch_trim_down";           //Pitch trim down.
public const string aileron_trim_left = "sim/flight_controls/aileron_trim_left";           //Aileron trim left.
public const string aileron_trim_right = "sim/flight_controls/aileron_trim_right";           //Aileron trim right.
public const string rudder_trim_left = "sim/flight_controls/rudder_trim_left";           //Rudder trim left.
public const string rudder_trim_right = "sim/flight_controls/rudder_trim_right";           //Rudder trim right.
public const string gyro_rotor_trim_up = "sim/flight_controls/gyro_rotor_trim_up";           //Gyro rotor trim up.
public const string gyro_rotor_trim_down = "sim/flight_controls/gyro_rotor_trim_down";           //Gyro rotor trim down.
public const string rotor_rpm_trim_up = "sim/flight_controls/rotor_rpm_trim_up";           //Rotor RPM trim up.
public const string rotor_rpm_trim_down = "sim/flight_controls/rotor_rpm_trim_down";           //Rotor RPM trim down.
public const string pitch_trim_takeoff = "sim/flight_controls/pitch_trim_takeoff";           //Pitch trim takeoff.
public const string aileron_trim_center = "sim/flight_controls/aileron_trim_center";           //Aileron trim center.
public const string rudder_trim_center = "sim/flight_controls/rudder_trim_center";           //Rudder trim center.
public const string rudder_lft = "sim/flight_controls/rudder_lft";           //Rudder left.
public const string rudder_ctr = "sim/flight_controls/rudder_ctr";           //Rudder center.
public const string rudder_rgt = "sim/flight_controls/rudder_rgt";           //Rudder right.