public const string ls_1l = "sim/FMS/ls_1l";           //FMS: line select 1l
public const string ls_2l = "sim/FMS/ls_2l";           //FMS: line select 2l
public const string ls_3l = "sim/FMS/ls_3l";           //FMS: line select 3l
public const string ls_4l = "sim/FMS/ls_4l";           //FMS: line select 4l
public const string ls_5l = "sim/FMS/ls_5l";           //FMS: line select 5l
public const string ls_6l = "sim/FMS/ls_6l";           //FMS: line select 6l
public const string ls_1r = "sim/FMS/ls_1r";           //FMS: line select 1r
public const string ls_2r = "sim/FMS/ls_2r";           //FMS: line select 2r
public const string ls_3r = "sim/FMS/ls_3r";           //FMS: line select 3r
public const string ls_4r = "sim/FMS/ls_4r";           //FMS: line select 4r
public const string ls_5r = "sim/FMS/ls_5r";           //FMS: line select 5r
public const string ls_6r = "sim/FMS/ls_6r";           //FMS: line select 6r
public const string index = "sim/FMS/index";           //FMS: INDEX
public const string fpln = "sim/FMS/fpln";           //FMS: FPLN
public const string clb = "sim/FMS/clb";           //FMS: CLB
public const string crz = "sim/FMS/crz";           //FMS: CRZ
public const string des = "sim/FMS/des";           //FMS: DES
public const string dir_intc = "sim/FMS/dir_intc";           //FMS: DIR/INTC
public const string legs = "sim/FMS/legs";           //FMS: FPLN
public const string dep_arr = "sim/FMS/dep_arr";           //FMS: DEP/ARR
public const string hold = "sim/FMS/hold";           //FMS: HOLD
public const string prog = "sim/FMS/prog";           //FMS: PROG
public const string exec = "sim/FMS/exec";           //FMS: EXEC
public const string fix = "sim/FMS/fix";           //FMS: FIX
public const string navrad = "sim/FMS/navrad";           //FMS: NAVRAD
public const string init = "sim/FMS/init";           //FMS: init
public const string prev = "sim/FMS/prev";           //FMS: prev
public const string next = "sim/FMS/next";           //FMS: next
public const string clear = "sim/FMS/clear";           //FMS: clear
public const string direct = "sim/FMS/direct";           //FMS: direct
public const string sign = "sim/FMS/sign";           //FMS: sign
public const string type_apt = "sim/FMS/type_apt";           //FMS: apt
public const string type_vor = "sim/FMS/type_vor";           //FMS: vor
public const string type_ndb = "sim/FMS/type_ndb";           //FMS: ndb
public const string type_fix = "sim/FMS/type_fix";           //FMS: fix
public const string type_latlon = "sim/FMS/type_latlon";           //FMS: lat/lon
public const string key_0 = "sim/FMS/key_0";           //FMS: key_0
public const string key_1 = "sim/FMS/key_1";           //FMS: key_1
public const string key_2 = "sim/FMS/key_2";           //FMS: key_2
public const string key_3 = "sim/FMS/key_3";           //FMS: key_3
public const string key_4 = "sim/FMS/key_4";           //FMS: key_4
public const string key_5 = "sim/FMS/key_5";           //FMS: key_5
public const string key_6 = "sim/FMS/key_6";           //FMS: key_6
public const string key_7 = "sim/FMS/key_7";           //FMS: key_7
public const string key_8 = "sim/FMS/key_8";           //FMS: key_8
public const string key_9 = "sim/FMS/key_9";           //FMS: key_9
public const string key_A = "sim/FMS/key_A";           //FMS: key_A
public const string key_B = "sim/FMS/key_B";           //FMS: key_B
public const string key_C = "sim/FMS/key_C";           //FMS: key_C
public const string key_D = "sim/FMS/key_D";           //FMS: key_D
public const string key_E = "sim/FMS/key_E";           //FMS: key_E
public const string key_F = "sim/FMS/key_F";           //FMS: key_F
public const string key_G = "sim/FMS/key_G";           //FMS: key_G
public const string key_H = "sim/FMS/key_H";           //FMS: key_H
public const string key_I = "sim/FMS/key_I";           //FMS: key_I
public const string key_J = "sim/FMS/key_J";           //FMS: key_J
public const string key_K = "sim/FMS/key_K";           //FMS: key_K
public const string key_L = "sim/FMS/key_L";           //FMS: key_L
public const string key_M = "sim/FMS/key_M";           //FMS: key_M
public const string key_N = "sim/FMS/key_N";           //FMS: key_N
public const string key_O = "sim/FMS/key_O";           //FMS: key_O
public const string key_P = "sim/FMS/key_P";           //FMS: key_P
public const string key_Q = "sim/FMS/key_Q";           //FMS: key_Q
public const string key_R = "sim/FMS/key_R";           //FMS: key_R
public const string key_S = "sim/FMS/key_S";           //FMS: key_S
public const string key_T = "sim/FMS/key_T";           //FMS: key_T
public const string key_U = "sim/FMS/key_U";           //FMS: key_U
public const string key_V = "sim/FMS/key_V";           //FMS: key_V
public const string key_W = "sim/FMS/key_W";           //FMS: key_W
public const string key_X = "sim/FMS/key_X";           //FMS: key_X
public const string key_Y = "sim/FMS/key_Y";           //FMS: key_Y
public const string key_Z = "sim/FMS/key_Z";           //FMS: key_Z
public const string key_period = "sim/FMS/key_period";           //FMS: key_period
public const string key_minus = "sim/FMS/key_minus";           //FMS: key_minus
public const string key_slash = "sim/FMS/key_slash";           //FMS: key_slash
public const string key_back = "sim/FMS/key_back";           //FMS: key_back
public const string key_space = "sim/FMS/key_space";           //FMS: key_space
public const string key_load = "sim/FMS/key_load";           //FMS: key_load
public const string key_save = "sim/FMS/key_save";           //FMS: key_save
public const string key_delete = "sim/FMS/key_delete";           //FMS: key_delete
public const string key_clear = "sim/FMS/key_clear";           //FMS: key_clear
public const string CDU_popup = "sim/FMS/CDU_popup";           //FMS: CDU popup
public const string CDU_popout = "sim/FMS/CDU_popout";           //FMS: pop out CDU window
public const string fix_next = "sim/FMS/fix_next";           //FMS: next fix
public const string fix_prev = "sim/FMS/fix_prev";           //FMS: prev fix