public const string ls_1l = "sim/FMS2/ls_1l";           //FMS2: line select 1l
public const string ls_2l = "sim/FMS2/ls_2l";           //FMS2: line select 2l
public const string ls_3l = "sim/FMS2/ls_3l";           //FMS2: line select 3l
public const string ls_4l = "sim/FMS2/ls_4l";           //FMS2: line select 4l
public const string ls_5l = "sim/FMS2/ls_5l";           //FMS2: line select 5l
public const string ls_6l = "sim/FMS2/ls_6l";           //FMS2: line select 6l
public const string ls_1r = "sim/FMS2/ls_1r";           //FMS2: line select 1r
public const string ls_2r = "sim/FMS2/ls_2r";           //FMS2: line select 2r
public const string ls_3r = "sim/FMS2/ls_3r";           //FMS2: line select 3r
public const string ls_4r = "sim/FMS2/ls_4r";           //FMS2: line select 4r
public const string ls_5r = "sim/FMS2/ls_5r";           //FMS2: line select 5r
public const string ls_6r = "sim/FMS2/ls_6r";           //FMS2: line select 6r
public const string index = "sim/FMS2/index";           //FMS: INDEX
public const string fpln = "sim/FMS2/fpln";           //FMS2: FPLN
public const string clb = "sim/FMS2/clb";           //FMS2: CLB
public const string crz = "sim/FMS2/crz";           //FMS2: CRZ
public const string des = "sim/FMS2/des";           //FMS2: DES
public const string dir_intc = "sim/FMS2/dir_intc";           //FMS2: DIR/INTC
public const string legs = "sim/FMS2/legs";           //FMS2: FPLN
public const string dep_arr = "sim/FMS2/dep_arr";           //FMS2: DEP/ARR
public const string hold = "sim/FMS2/hold";           //FMS2: HOLD
public const string prog = "sim/FMS2/prog";           //FMS2: PROG
public const string exec = "sim/FMS2/exec";           //FMS2: EXEC
public const string fix = "sim/FMS2/fix";           //FMS2: FIX
public const string navrad = "sim/FMS2/navrad";           //FMS2: NAVRAD
public const string prev = "sim/FMS2/prev";           //FMS2: prev
public const string next = "sim/FMS2/next";           //FMS2: next
public const string key_0 = "sim/FMS2/key_0";           //FMS2: key_0
public const string key_1 = "sim/FMS2/key_1";           //FMS2: key_1
public const string key_2 = "sim/FMS2/key_2";           //FMS2: key_2
public const string key_3 = "sim/FMS2/key_3";           //FMS2: key_3
public const string key_4 = "sim/FMS2/key_4";           //FMS2: key_4
public const string key_5 = "sim/FMS2/key_5";           //FMS2: key_5
public const string key_6 = "sim/FMS2/key_6";           //FMS2: key_6
public const string key_7 = "sim/FMS2/key_7";           //FMS2: key_7
public const string key_8 = "sim/FMS2/key_8";           //FMS2: key_8
public const string key_9 = "sim/FMS2/key_9";           //FMS2: key_9
public const string key_A = "sim/FMS2/key_A";           //FMS2: key_A
public const string key_B = "sim/FMS2/key_B";           //FMS2: key_B
public const string key_C = "sim/FMS2/key_C";           //FMS2: key_C
public const string key_D = "sim/FMS2/key_D";           //FMS2: key_D
public const string key_E = "sim/FMS2/key_E";           //FMS2: key_E
public const string key_F = "sim/FMS2/key_F";           //FMS2: key_F
public const string key_G = "sim/FMS2/key_G";           //FMS2: key_G
public const string key_H = "sim/FMS2/key_H";           //FMS2: key_H
public const string key_I = "sim/FMS2/key_I";           //FMS2: key_I
public const string key_J = "sim/FMS2/key_J";           //FMS2: key_J
public const string key_K = "sim/FMS2/key_K";           //FMS2: key_K
public const string key_L = "sim/FMS2/key_L";           //FMS2: key_L
public const string key_M = "sim/FMS2/key_M";           //FMS2: key_M
public const string key_N = "sim/FMS2/key_N";           //FMS2: key_N
public const string key_O = "sim/FMS2/key_O";           //FMS2: key_O
public const string key_P = "sim/FMS2/key_P";           //FMS2: key_P
public const string key_Q = "sim/FMS2/key_Q";           //FMS2: key_Q
public const string key_R = "sim/FMS2/key_R";           //FMS2: key_R
public const string key_S = "sim/FMS2/key_S";           //FMS2: key_S
public const string key_T = "sim/FMS2/key_T";           //FMS2: key_T
public const string key_U = "sim/FMS2/key_U";           //FMS2: key_U
public const string key_V = "sim/FMS2/key_V";           //FMS2: key_V
public const string key_W = "sim/FMS2/key_W";           //FMS2: key_W
public const string key_X = "sim/FMS2/key_X";           //FMS2: key_X
public const string key_Y = "sim/FMS2/key_Y";           //FMS2: key_Y
public const string key_Z = "sim/FMS2/key_Z";           //FMS2: key_Z
public const string key_period = "sim/FMS2/key_period";           //FMS2: key_period
public const string key_minus = "sim/FMS2/key_minus";           //FMS2: key_minus
public const string key_slash = "sim/FMS2/key_slash";           //FMS2: key_slash
public const string key_back = "sim/FMS2/key_back";           //FMS2: key_back
public const string key_space = "sim/FMS2/key_space";           //FMS2: key_space
public const string key_delete = "sim/FMS2/key_delete";           //FMS2: key_delete
public const string key_clear = "sim/FMS2/key_clear";           //FMS2: key_clear
public const string CDU_popout = "sim/FMS2/CDU_popout";           //FMS2: pop out CDU window
public const string CDU_popup = "sim/FMS2/CDU_popup";           //FMS2: CDU popup