public const string fuel_tank_selector_lft_one = "sim/fuel/fuel_tank_selector_lft_one";                //Select fuel tank left one.
public const string fuel_tank_selector_rgt_one = "sim/fuel/fuel_tank_selector_rgt_one";                //Select fuel tank right one.
public const string fuel_tank_pump_1_on = "sim/fuel/fuel_tank_pump_1_on";                       //Fuel pump for tank #1 on.
public const string fuel_tank_pump_2_on = "sim/fuel/fuel_tank_pump_2_on";                       //Fuel pump for tank #2 on.
public const string fuel_tank_pump_3_on = "sim/fuel/fuel_tank_pump_3_on";                       //Fuel pump for tank #3 on.
public const string fuel_tank_pump_4_on = "sim/fuel/fuel_tank_pump_4_on";                       //Fuel pump for tank #4 on.
public const string fuel_tank_pump_5_on = "sim/fuel/fuel_tank_pump_5_on";                       //Fuel pump for tank #5 on.
public const string fuel_tank_pump_6_on = "sim/fuel/fuel_tank_pump_6_on";                       //Fuel pump for tank #6 on.
public const string fuel_tank_pump_7_on = "sim/fuel/fuel_tank_pump_7_on";                       //Fuel pump for tank #7 on.
public const string fuel_tank_pump_8_on = "sim/fuel/fuel_tank_pump_8_on";                       //Fuel pump for tank #8 on.
public const string fuel_tank_pump_9_on = "sim/fuel/fuel_tank_pump_9_on";                       //Fuel pump for tank #9 on.
public const string fuel_tank_pump_1_off = "sim/fuel/fuel_tank_pump_1_off";                      //Fuel pump for tank #1 off.
public const string fuel_tank_pump_2_off = "sim/fuel/fuel_tank_pump_2_off";                      //Fuel pump for tank #2 off.
public const string fuel_tank_pump_3_off = "sim/fuel/fuel_tank_pump_3_off";                      //Fuel pump for tank #3 off.
public const string fuel_tank_pump_4_off = "sim/fuel/fuel_tank_pump_4_off";                      //Fuel pump for tank #4 off.
public const string fuel_tank_pump_5_off = "sim/fuel/fuel_tank_pump_5_off";                      //Fuel pump for tank #5 off.
public const string fuel_tank_pump_6_off = "sim/fuel/fuel_tank_pump_6_off";                      //Fuel pump for tank #6 off.
public const string fuel_tank_pump_7_off = "sim/fuel/fuel_tank_pump_7_off";                      //Fuel pump for tank #7 off.
public const string fuel_tank_pump_8_off = "sim/fuel/fuel_tank_pump_8_off";                      //Fuel pump for tank #8 off.
public const string fuel_tank_pump_9_off = "sim/fuel/fuel_tank_pump_9_off";                      //Fuel pump for tank #9 off.
public const string fuel_selector_none = "sim/fuel/fuel_selector_none";                        //Set fuel selector to none (shut off).
public const string fuel_selector_lft = "sim/fuel/fuel_selector_lft";                         //Set fuel selector to left tanks.
public const string fuel_selector_ctr = "sim/fuel/fuel_selector_ctr";                         //Set fuel selector to center tanks.
public const string fuel_selector_rgt = "sim/fuel/fuel_selector_rgt";                         //Set fuel selector to right tanks.
public const string fuel_selector_all = "sim/fuel/fuel_selector_all";                         //Set fuel selector to all tanks.
public const string fuel_transfer_to_lft = "sim/fuel/fuel_transfer_to_lft";                      //Transfer fuel to left.
public const string fuel_transfer_to_ctr = "sim/fuel/fuel_transfer_to_ctr";                      //Transfer fuel to center.
public const string fuel_transfer_to_rgt = "sim/fuel/fuel_transfer_to_rgt";                      //Transfer fuel to right.
public const string fuel_transfer_to_off = "sim/fuel/fuel_transfer_to_off";                      //Transfer fuel to none.
public const string fuel_transfer_from_lft = "sim/fuel/fuel_transfer_from_lft";                    //Transfer fuel from left.
public const string fuel_transfer_from_ctr = "sim/fuel/fuel_transfer_from_ctr";                    //Transfer fuel from center.
public const string fuel_transfer_from_rgt = "sim/fuel/fuel_transfer_from_rgt";                    //Transfer fuel from right.
public const string fuel_transfer_from_off = "sim/fuel/fuel_transfer_from_off";                    //Transfer fuel from none.
public const string fuel_crossfeed_from_lft_tank = "sim/fuel/fuel_crossfeed_from_lft_tank";              //Cross-feed fuel from left tank.
public const string fuel_crossfeed_off = "sim/fuel/fuel_crossfeed_off";              //Cross-feed fuel off.
public const string fuel_crossfeed_from_rgt_tank = "sim/fuel/fuel_crossfeed_from_rgt_tank";              //Cross-feed fuel from right tank.
public const string fuel_firewall_valve_lft_open = "sim/fuel/fuel_firewall_valve_lft_open";              //Firewall fuel valve left open.
public const string fuel_firewall_valve_lft_closed = "sim/fuel/fuel_firewall_valve_lft_closed";            //Firewall fuel valve left closed.
public const string fuel_firewall_valve_rgt_open = "sim/fuel/fuel_firewall_valve_rgt_open";              //Firewall fuel valve right open.
public const string fuel_firewall_valve_rgt_closed = "sim/fuel/fuel_firewall_valve_rgt_closed";            //Firewall fuel valve right closed.
public const string fuel_pumps_on = "sim/fuel/fuel_pumps_on";                             //Fuel pumps on.
public const string fuel_pumps_off = "sim/fuel/fuel_pumps_off";                            //Fuel pumps off.
public const string fuel_pumps_tog = "sim/fuel/fuel_pumps_tog";                            //Fuel pumps toggle.
public const string fuel_pump_1_on = "sim/fuel/fuel_pump_1_on";                            //Fuel pump for engine #1 on.
public const string fuel_pump_2_on = "sim/fuel/fuel_pump_2_on";                            //Fuel pump for engine #2 on.
public const string fuel_pump_3_on = "sim/fuel/fuel_pump_3_on";                            //Fuel pump for engine #3 on.
public const string fuel_pump_4_on = "sim/fuel/fuel_pump_4_on";                            //Fuel pump for engine #4 on.
public const string fuel_pump_5_on = "sim/fuel/fuel_pump_5_on";                            //Fuel pump for engine #5 on.
public const string fuel_pump_6_on = "sim/fuel/fuel_pump_6_on";                            //Fuel pump for engine #6 on.
public const string fuel_pump_7_on = "sim/fuel/fuel_pump_7_on";                            //Fuel pump for engine #7 on.
public const string fuel_pump_8_on = "sim/fuel/fuel_pump_8_on";                            //Fuel pump for engine #8 on.
public const string fuel_pump_1_off = "sim/fuel/fuel_pump_1_off";                           //Fuel pump for engine #1 off.
public const string fuel_pump_2_off = "sim/fuel/fuel_pump_2_off";                           //Fuel pump for engine #2 off.
public const string fuel_pump_3_off = "sim/fuel/fuel_pump_3_off";                           //Fuel pump for engine #3 off.
public const string fuel_pump_4_off = "sim/fuel/fuel_pump_4_off";                           //Fuel pump for engine #4 off.
public const string fuel_pump_5_off = "sim/fuel/fuel_pump_5_off";                           //Fuel pump for engine #5 off.
public const string fuel_pump_6_off = "sim/fuel/fuel_pump_6_off";                           //Fuel pump for engine #6 off.
public const string fuel_pump_7_off = "sim/fuel/fuel_pump_7_off";                           //Fuel pump for engine #7 off.
public const string fuel_pump_8_off = "sim/fuel/fuel_pump_8_off";                           //Fuel pump for engine #8 off.
public const string fuel_pump_1_tog = "sim/fuel/fuel_pump_1_tog";                           //Fuel pump for engine #1 toggle.
public const string fuel_pump_2_tog = "sim/fuel/fuel_pump_2_tog";                           //Fuel pump for engine #2 toggle.
public const string fuel_pump_3_tog = "sim/fuel/fuel_pump_3_tog";                           //Fuel pump for engine #3 toggle.
public const string fuel_pump_4_tog = "sim/fuel/fuel_pump_4_tog";                           //Fuel pump for engine #4 toggle.
public const string fuel_pump_5_tog = "sim/fuel/fuel_pump_5_tog";                           //Fuel pump for engine #5 toggle.
public const string fuel_pump_6_tog = "sim/fuel/fuel_pump_6_tog";                           //Fuel pump for engine #6 toggle.
public const string fuel_pump_7_tog = "sim/fuel/fuel_pump_7_tog";                           //Fuel pump for engine #7 toggle.
public const string fuel_pump_8_tog = "sim/fuel/fuel_pump_8_tog";                           //Fuel pump for engine #8 toggle.
public const string fuel_pump_1_prime = "sim/fuel/fuel_pump_1_prime";                         //Fuel pump prime for engine #1 on.
public const string fuel_pump_2_prime = "sim/fuel/fuel_pump_2_prime";                         //Fuel pump prime for engine #2 on.
public const string fuel_pump_3_prime = "sim/fuel/fuel_pump_3_prime";                         //Fuel pump prime for engine #3 on.
public const string fuel_pump_4_prime = "sim/fuel/fuel_pump_4_prime";                         //Fuel pump prime for engine #4 on.
public const string fuel_pump_5_prime = "sim/fuel/fuel_pump_5_prime";                         //Fuel pump prime for engine #5 on.
public const string fuel_pump_6_prime = "sim/fuel/fuel_pump_6_prime";                         //Fuel pump prime for engine #6 on.
public const string fuel_pump_7_prime = "sim/fuel/fuel_pump_7_prime";                         //Fuel pump prime for engine #7 on.
public const string fuel_pump_8_prime = "sim/fuel/fuel_pump_8_prime";                         //Fuel pump prime for engine #8 on.
public const string indicate_aux = "sim/fuel/indicate_aux";           //Fuel tanks show auxiliary tanks.