public const string action = "sim/general/action";           //General action command.
public const string left = "sim/general/left";           //Move view left.
public const string right = "sim/general/right";           //Move view right.
public const string up = "sim/general/up";           //Move view up.
public const string down = "sim/general/down";           //Move view down.
public const string forward = "sim/general/forward";           //Move view forward.
public const string backward = "sim/general/backward";           //Move view backward.
public const string zoom_in = "sim/general/zoom_in";           //Zoom in.
public const string zoom_out = "sim/general/zoom_out";           //Zoom out.
public const string hat_switch_left = "sim/general/hat_switch_left";           //Hat switch left.
public const string hat_switch_right = "sim/general/hat_switch_right";           //Hat switch right.
public const string hat_switch_up = "sim/general/hat_switch_up";           //Hat switch up.
public const string hat_switch_down = "sim/general/hat_switch_down";           //Hat switch down.
public const string hat_switch_up_left = "sim/general/hat_switch_up_left";           //Hat switch up + left.
public const string hat_switch_up_right = "sim/general/hat_switch_up_right";           //Hat switch up + right.
public const string hat_switch_down_left = "sim/general/hat_switch_down_left";           //Hat switch down + left.
public const string hat_switch_down_right = "sim/general/hat_switch_down_right";           //Hat switch down + right.
public const string left_fast = "sim/general/left_fast";           //Move view left fast.
public const string right_fast = "sim/general/right_fast";           //Move view right fast.
public const string up_fast = "sim/general/up_fast";           //Move view up fast.
public const string down_fast = "sim/general/down_fast";           //Move view down fast.
public const string forward_fast = "sim/general/forward_fast";           //Move view forward fast.
public const string backward_fast = "sim/general/backward_fast";           //Move view backward fast.
public const string zoom_in_fast = "sim/general/zoom_in_fast";           //Zoom in fast.
public const string zoom_out_fast = "sim/general/zoom_out_fast";           //Zoom out fast.
public const string left_slow = "sim/general/left_slow";           //Move view left slow.
public const string right_slow = "sim/general/right_slow";           //Move view right slow.
public const string up_slow = "sim/general/up_slow";           //Move view up slow.
public const string down_slow = "sim/general/down_slow";           //Move view down slow.
public const string forward_slow = "sim/general/forward_slow";           //Move view forward slow.
public const string backward_slow = "sim/general/backward_slow";           //Move view backward slow.
public const string zoom_in_slow = "sim/general/zoom_in_slow";           //Zoom in slow.
public const string zoom_out_slow = "sim/general/zoom_out_slow";           //Zoom out slow.
public const string rot_up = "sim/general/rot_up";           //Rotate view: tilt up.
public const string rot_down = "sim/general/rot_down";           //Rotate view: tilt down.
public const string rot_left = "sim/general/rot_left";           //Rotate view: pan left.
public const string rot_right = "sim/general/rot_right";           //Rotate view: pan right.
public const string rot_up_fast = "sim/general/rot_up_fast";           //Rotate view: tilt up fast.
public const string rot_down_fast = "sim/general/rot_down_fast";           //Rotate view: tilt down fast.
public const string rot_left_fast = "sim/general/rot_left_fast";           //Rotate view: pan left fast.
public const string rot_right_fast = "sim/general/rot_right_fast";           //Rotate view: pan right fast.
public const string rot_up_slow = "sim/general/rot_up_slow";           //Rotate view: tilt up slow.
public const string rot_down_slow = "sim/general/rot_down_slow";           //Rotate view: tilt down slow.
public const string rot_left_slow = "sim/general/rot_left_slow";           //Rotate view: pan left slow.
public const string rot_right_slow = "sim/general/rot_right_slow";           //Rotate view: pan right slow.
public const string toggle_artificial_stab_win = "sim/general/toggle_artificial_stab_win";           //Toggle the artificial stability constants window.
public const string toggle_traffic_paths = "sim/general/toggle_traffic_paths";           //Toggle display of traffic paths.
public const string toggle_autopilot_constants_win = "sim/general/toggle_autopilot_constants_win";           //Toggle the autopilot constants window.
public const string toggle_fadec_win = "sim/general/toggle_fadec_win";           //Toggle the FADEC constants window.
public const string toggle_control_deflections_win = "sim/general/toggle_control_deflections_win";           //Toggle the control deflections window.
public const string toggle_bouncers_win = "sim/general/toggle_bouncers_win";           //Toggle the bouncers window.
public const string toggle_weapon_guidance_win = "sim/general/toggle_weapon_guidance_win";           //Toggle the weapon guidance window.
public const string toggle_projection_win = "sim/general/toggle_projection_win";           //Toggle the projection configuration window.