public const string anti_ice_toggle = "sim/ice/anti_ice_toggle";      //Anti-ice: toggle all.
public const string alternate_static_port = "sim/ice/alternate_static_port";      //Toggle alternate static port.
public const string pitot_heat0_on = "sim/ice/pitot_heat0_on";      //Anti-ice: left pitot heat on.
public const string pitot_heat1_on = "sim/ice/pitot_heat1_on";      //Anti-ice: right pitot heat on.
public const string pitot_heat0_off = "sim/ice/pitot_heat0_off";      //Anti-ice: left pitot heat off.
public const string pitot_heat1_off = "sim/ice/pitot_heat1_off";      //Anti-ice: right pitot heat off.
public const string pitot_heat0_tog = "sim/ice/pitot_heat0_tog";      //Anti-ice: left pitot heat toggle.
public const string pitot_heat1_tog = "sim/ice/pitot_heat1_tog";      //Anti-ice: right pitot heat toggle.
public const string static_heat0_on = "sim/ice/static_heat0_on";      //Anti-ice: left static heat on.
public const string static_heat1_on = "sim/ice/static_heat1_on";      //Anti-ice: right static heat on.
public const string static_heat0_off = "sim/ice/static_heat0_off";      //Anti-ice: left static heat off.
public const string static_heat1_off = "sim/ice/static_heat1_off";      //Anti-ice: right static heat off.
public const string AOA_heat0_on = "sim/ice/AOA_heat0_on";      //Anti-ice: AOA on.
public const string AOA_heat1_on = "sim/ice/AOA_heat1_on";      //Anti-ice: AOA on.
public const string AOA_heat0_off = "sim/ice/AOA_heat0_off";      //Anti-ice: AOA off.
public const string AOA_heat1_off = "sim/ice/AOA_heat1_off";      //Anti-ice: AOA off.
public const string AOA_heat0_tog = "sim/ice/AOA_heat0_tog";      //Anti-ice: AOA toggle.
public const string AOA_heat1_tog = "sim/ice/AOA_heat1_tog";      //Anti-ice: AOA toggle.
public const string window_heat_on = "sim/ice/window_heat_on";      //Anti-ice: window heat on.
public const string window_heat_off = "sim/ice/window_heat_off";      //Anti-ice: window heat off.
public const string window_heat_tog = "sim/ice/window_heat_tog";      //Anti-ice: window heat toggle.
public const string wing_heat_on = "sim/ice/wing_heat_on";      //Anti-ice: all wing, de-ice on.
public const string wing_heat0_on = "sim/ice/wing_heat0_on";      //Anti-ice: left wing, de-ice on.
public const string wing_heat1_on = "sim/ice/wing_heat1_on";      //Anti-ice: right wing, de-ice on.
public const string wing_heat_off = "sim/ice/wing_heat_off";      //Anti-ice: all wing, de-ice off.
public const string wing_heat0_off = "sim/ice/wing_heat0_off";      //Anti-ice: left wing, de-ice off.
public const string wing_heat1_off = "sim/ice/wing_heat1_off";      //Anti-ice: right wing, de-ice off.
public const string wing_heat_tog = "sim/ice/wing_heat_tog";      //Anti-ice: all wing, de-ice toggle.
public const string wing_heat0_tog = "sim/ice/wing_heat0_tog";      //Anti-ice: left wing, de-ice toggle.
public const string wing_heat1_tog = "sim/ice/wing_heat1_tog";      //Anti-ice: right wing, de-ice toggle.
public const string inlet_heat0_on = "sim/ice/inlet_heat0_on";      //Anti-ice: engine #1 inlet heat on.
public const string inlet_heat1_on = "sim/ice/inlet_heat1_on";      //Anti-ice: engine #2 inlet heat on.
public const string inlet_heat2_on = "sim/ice/inlet_heat2_on";      //Anti-ice: engine #3 inlet heat on.
public const string inlet_heat3_on = "sim/ice/inlet_heat3_on";      //Anti-ice: engine #4 inlet heat on.
public const string inlet_heat4_on = "sim/ice/inlet_heat4_on";      //Anti-ice: engine #5 inlet heat on.
public const string inlet_heat5_on = "sim/ice/inlet_heat5_on";      //Anti-ice: engine #6 inlet heat on.
public const string inlet_heat6_on = "sim/ice/inlet_heat6_on";      //Anti-ice: engine #7 inlet heat on.
public const string inlet_heat7_on = "sim/ice/inlet_heat7_on";      //Anti-ice: engine #8 inlet heat on.
public const string inlet_heat0_off = "sim/ice/inlet_heat0_off";      //Anti-ice: engine #1 inlet heat off.
public const string inlet_heat1_off = "sim/ice/inlet_heat1_off";      //Anti-ice: engine #2 inlet heat off.
public const string inlet_heat2_off = "sim/ice/inlet_heat2_off";      //Anti-ice: engine #3 inlet heat off.
public const string inlet_heat3_off = "sim/ice/inlet_heat3_off";      //Anti-ice: engine #4 inlet heat off.
public const string inlet_heat4_off = "sim/ice/inlet_heat4_off";      //Anti-ice: engine #5 inlet heat off.
public const string inlet_heat5_off = "sim/ice/inlet_heat5_off";      //Anti-ice: engine #6 inlet heat off.
public const string inlet_heat6_off = "sim/ice/inlet_heat6_off";      //Anti-ice: engine #7 inlet heat off.
public const string inlet_heat7_off = "sim/ice/inlet_heat7_off";      //Anti-ice: engine #8 inlet heat off.
public const string inlet_heat0_tog = "sim/ice/inlet_heat0_tog";      //Anti-ice: engine #1 inlet heat toggle.
public const string inlet_heat1_tog = "sim/ice/inlet_heat1_tog";      //Anti-ice: engine #2 inlet heat toggle.
public const string inlet_heat2_tog = "sim/ice/inlet_heat2_tog";      //Anti-ice: engine #3 inlet heat toggle.
public const string inlet_heat3_tog = "sim/ice/inlet_heat3_tog";      //Anti-ice: engine #4 inlet heat toggle.
public const string inlet_heat4_tog = "sim/ice/inlet_heat4_tog";      //Anti-ice: engine #5 inlet heat toggle.
public const string inlet_heat5_tog = "sim/ice/inlet_heat5_tog";      //Anti-ice: engine #6 inlet heat toggle.
public const string inlet_heat6_tog = "sim/ice/inlet_heat6_tog";      //Anti-ice: engine #7 inlet heat toggle.
public const string inlet_heat7_tog = "sim/ice/inlet_heat7_tog";      //Anti-ice: engine #8 inlet heat toggle.
public const string prop_heat_on = "sim/ice/prop_heat_on";      //Anti-ice: all prop heat on.
public const string prop_heat_off = "sim/ice/prop_heat_off";      //Anti-ice: all prop heat off.
public const string prop_heat_tog = "sim/ice/prop_heat_tog";      //Anti-ice: all prop heat toggle.
public const string prop_heat0_on = "sim/ice/prop_heat0_on";      //Anti-ice: engine #1 prop heat on.
public const string prop_heat1_on = "sim/ice/prop_heat1_on";      //Anti-ice: engine #2 prop heat on.
public const string prop_heat2_on = "sim/ice/prop_heat2_on";      //Anti-ice: engine #3 prop heat on.
public const string prop_heat3_on = "sim/ice/prop_heat3_on";      //Anti-ice: engine #4 prop heat on.
public const string prop_heat4_on = "sim/ice/prop_heat4_on";      //Anti-ice: engine #5 prop heat on.
public const string prop_heat5_on = "sim/ice/prop_heat5_on";      //Anti-ice: engine #6 prop heat on.
public const string prop_heat6_on = "sim/ice/prop_heat6_on";      //Anti-ice: engine #7 prop heat on.
public const string prop_heat7_on = "sim/ice/prop_heat7_on";      //Anti-ice: engine #8 prop heat on.
public const string prop_heat0_off = "sim/ice/prop_heat0_off";      //Anti-ice: engine #1 prop heat off.
public const string prop_heat1_off = "sim/ice/prop_heat1_off";      //Anti-ice: engine #2 prop heat off.
public const string prop_heat2_off = "sim/ice/prop_heat2_off";      //Anti-ice: engine #3 prop heat off.
public const string prop_heat3_off = "sim/ice/prop_heat3_off";      //Anti-ice: engine #4 prop heat off.
public const string prop_heat4_off = "sim/ice/prop_heat4_off";      //Anti-ice: engine #5 prop heat off.
public const string prop_heat5_off = "sim/ice/prop_heat5_off";      //Anti-ice: engine #6 prop heat off.
public const string prop_heat6_off = "sim/ice/prop_heat6_off";      //Anti-ice: engine #7 prop heat off.
public const string prop_heat7_off = "sim/ice/prop_heat7_off";      //Anti-ice: engine #8 prop heat off.
public const string prop_heat0_tog = "sim/ice/prop_heat0_tog";      //Anti-ice: engine #1 prop heat toggle.
public const string prop_heat1_tog = "sim/ice/prop_heat1_tog";      //Anti-ice: engine #2 prop heat toggle.
public const string prop_heat2_tog = "sim/ice/prop_heat2_tog";      //Anti-ice: engine #3 prop heat toggle.
public const string prop_heat3_tog = "sim/ice/prop_heat3_tog";      //Anti-ice: engine #4 prop heat toggle.
public const string prop_heat4_tog = "sim/ice/prop_heat4_tog";      //Anti-ice: engine #5 prop heat toggle.
public const string prop_heat5_tog = "sim/ice/prop_heat5_tog";      //Anti-ice: engine #6 prop heat toggle.
public const string prop_heat6_tog = "sim/ice/prop_heat6_tog";      //Anti-ice: engine #7 prop heat toggle.
public const string prop_heat7_tog = "sim/ice/prop_heat7_tog";      //Anti-ice: engine #8 prop heat toggle.
public const string detect_on = "sim/ice/detect_on";      //Anti-ice: ice detection on.
public const string detect_off = "sim/ice/detect_off";      //Anti-ice: ice detection off.