public const string ECAM_mode_up = "sim/instruments/ECAM_mode_up";           //ECAM mode up.
public const string ECAM_mode_down = "sim/instruments/ECAM_mode_down";           //ECAM mode down.
public const string map_zoom_in = "sim/instruments/map_zoom_in";           //Zoom in EFIS map.
public const string map_zoom_out = "sim/instruments/map_zoom_out";           //Zoom out EFIS map.
public const string EFIS_wxr = "sim/instruments/EFIS_wxr";           //EFIS map weather.
public const string EFIS_tcas = "sim/instruments/EFIS_tcas";           //EFIS map TCAS.
public const string EFIS_apt = "sim/instruments/EFIS_apt";           //EFIS map airport.
public const string EFIS_fix = "sim/instruments/EFIS_fix";           //EFIS map fix.
public const string EFIS_vor = "sim/instruments/EFIS_vor";           //EFIS map VOR.
public const string EFIS_ndb = "sim/instruments/EFIS_ndb";           //EFIS map NDB.
public const string EFIS_page_up = "sim/instruments/EFIS_page_up";           //EFIS page up.
public const string EFIS_page_dn = "sim/instruments/EFIS_page_dn";           //EFIS page down.
public const string EFIS_mode_up = "sim/instruments/EFIS_mode_up";           //EFIS mode up (APP/VOR/MAP/PLN)
public const string EFIS_mode_dn = "sim/instruments/EFIS_mode_dn";           //EFIS mode down (PLN/MAP/VOR/APP)
public const string EFIS_1_pilot_sel_dn = "sim/instruments/EFIS_1_pilot_sel_dn";           //EFIS 1 selection pilot down (ADF/off/VOR)
public const string EFIS_1_pilot_sel_up = "sim/instruments/EFIS_1_pilot_sel_up";           //EFIS 1 selection pilot up (ADF/off/VOR)
public const string EFIS_1_copilot_sel_dn = "sim/instruments/EFIS_1_copilot_sel_dn";           //EFIS 1 selection copilot down (ADF/off/VOR)
public const string EFIS_1_copilot_sel_up = "sim/instruments/EFIS_1_copilot_sel_up";           //EFIS 1 selection copilot up (ADF/off/VOR)
public const string EFIS_2_pilot_sel_dn = "sim/instruments/EFIS_2_pilot_sel_dn";           //EFIS 2 selection pilot down (ADF/off/VOR)
public const string EFIS_2_pilot_sel_up = "sim/instruments/EFIS_2_pilot_sel_up";           //EFIS 2 selection pilot up (ADF/off/VOR)
public const string EFIS_2_copilot_sel_dn = "sim/instruments/EFIS_2_copilot_sel_dn";           //EFIS 2 selection copilot down (ADF/off/VOR)
public const string EFIS_2_copilot_sel_up = "sim/instruments/EFIS_2_copilot_sel_up";           //EFIS 2 selection copilot up (ADF/off/VOR)
public const string thermo_units_toggle = "sim/instruments/thermo_units_toggle";           //Toggle english/metric thermometer.
public const string barometer_2992 = "sim/instruments/barometer_2992";           //Baro pressure selection 2992.
public const string DG_sync_down = "sim/instruments/DG_sync_down";           //DG sync down.
public const string DG_sync_up = "sim/instruments/DG_sync_up";           //DG sync up.
public const string copilot_DG_sync_down = "sim/instruments/copilot_DG_sync_down";           //Copilot DG sync down.
public const string copilot_DG_sync_up = "sim/instruments/copilot_DG_sync_up";           //Copilot DG sync up.
public const string ah_ref_down = "sim/instruments/ah_ref_down";           //Horizon reference down a bit.
public const string ah_ref_up = "sim/instruments/ah_ref_up";           //Horizon reference up a bit.
public const string ah_ref_copilot_down = "sim/instruments/ah_ref_copilot_down";           //Horizon reference down a bit, copilot.
public const string ah_ref_copilot_up = "sim/instruments/ah_ref_copilot_up";           //Horizon reference down a bit, copilot.
public const string barometer_down = "sim/instruments/barometer_down";           //Baro selection down a bit.
public const string barometer_up = "sim/instruments/barometer_up";           //Baro selection up a bit.
public const string barometer_copilot_down = "sim/instruments/barometer_copilot_down";           //Baro selection down a bit, copilot.
public const string barometer_copilot_up = "sim/instruments/barometer_copilot_up";           //Baro selection up a bit, copilot.
public const string dh_ref_down = "sim/instruments/dh_ref_down";           //Decision-height reference down.
public const string dh_ref_up = "sim/instruments/dh_ref_up";           //Decision-height reference up.
public const string dh_ref_copilot_down = "sim/instruments/dh_ref_copilot_down";           //Decision-height reference copilot down.
public const string dh_ref_copilot_up = "sim/instruments/dh_ref_copilot_up";           //Decision-height reference copilot up.
public const string panel_bright_down = "sim/instruments/panel_bright_down";           //Panel brightness down a bit.
public const string panel_bright_up = "sim/instruments/panel_bright_up";           //Panel brightness up a bit.
public const string instrument_bright_down = "sim/instruments/instrument_bright_down";           //Instrument brightness down a bit.
public const string instrument_bright_up = "sim/instruments/instrument_bright_up";           //Instrument brightness up a bit.
public const string timer_start_stop = "sim/instruments/timer_start_stop";           //Start or stop the timer.
public const string timer_reset = "sim/instruments/timer_reset";           //Reset the timer.
public const string timer_show_date = "sim/instruments/timer_show_date";           //Show date on the chrono.
public const string timer_mode = "sim/instruments/timer_mode";           //Timer/clock mode for chronos.
public const string timer_cycle = "sim/instruments/timer_cycle";           //Timer start/stop/reset.
public const string timer_is_GMT = "sim/instruments/timer_is_GMT";           //Timer is GMT.