public const string nav_lights_on = "sim/lights/nav_lights_on";           //Nav lights on.
public const string nav_lights_off = "sim/lights/nav_lights_off";           //Nav lights off.
public const string nav_lights_toggle = "sim/lights/nav_lights_toggle";           //Nav lights toggle.
public const string beacon_lights_on = "sim/lights/beacon_lights_on";           //Beacon lights on.
public const string beacon_lights_off = "sim/lights/beacon_lights_off";           //Beacon lights off.
public const string beacon_lights_toggle = "sim/lights/beacon_lights_toggle";           //Beacon lights toggle.
public const string strobe_lights_on = "sim/lights/strobe_lights_on";           //Strobe lights on.
public const string strobe_lights_off = "sim/lights/strobe_lights_off";           //Strobe lights off.
public const string strobe_lights_toggle = "sim/lights/strobe_lights_toggle";           //Strobe lights toggle.
public const string taxi_lights_on = "sim/lights/taxi_lights_on";           //Taxi lights on.
public const string taxi_lights_off = "sim/lights/taxi_lights_off";           //Taxi lights off.
public const string taxi_lights_toggle = "sim/lights/taxi_lights_toggle";           //Taxi lights toggle.
public const string landing_lights_on = "sim/lights/landing_lights_on";           //Landing lights on.
public const string landing_lights_off = "sim/lights/landing_lights_off";           //Landing lights off.
public const string landing_lights_toggle = "sim/lights/landing_lights_toggle";           //Landing lights toggle.
public const string landing_01_light_on = "sim/lights/landing_01_light_on";      //Landing light 01 on.
public const string landing_02_light_on = "sim/lights/landing_02_light_on";      //Landing light 02 on.
public const string landing_03_light_on = "sim/lights/landing_03_light_on";      //Landing light 03 on.
public const string landing_04_light_on = "sim/lights/landing_04_light_on";      //Landing light 04 on.
public const string landing_05_light_on = "sim/lights/landing_05_light_on";      //Landing light 05 on.
public const string landing_06_light_on = "sim/lights/landing_06_light_on";      //Landing light 06 on.
public const string landing_07_light_on = "sim/lights/landing_07_light_on";      //Landing light 07 on.
public const string landing_08_light_on = "sim/lights/landing_08_light_on";      //Landing light 08 on.
public const string landing_09_light_on = "sim/lights/landing_09_light_on";      //Landing light 09 on.
public const string landing_10_light_on = "sim/lights/landing_10_light_on";      //Landing light 10 on.
public const string landing_11_light_on = "sim/lights/landing_11_light_on";      //Landing light 11 on.
public const string landing_12_light_on = "sim/lights/landing_12_light_on";      //Landing light 12 on.
public const string landing_13_light_on = "sim/lights/landing_13_light_on";      //Landing light 13 on.
public const string landing_14_light_on = "sim/lights/landing_14_light_on";      //Landing light 14 on.
public const string landing_15_light_on = "sim/lights/landing_15_light_on";      //Landing light 15 on.
public const string landing_16_light_on = "sim/lights/landing_16_light_on";      //Landing light 16 on.
public const string landing_01_light_off = "sim/lights/landing_01_light_off";      //Landing light 01 off.
public const string landing_02_light_off = "sim/lights/landing_02_light_off";      //Landing light 02 off.
public const string landing_03_light_off = "sim/lights/landing_03_light_off";      //Landing light 03 off.
public const string landing_04_light_off = "sim/lights/landing_04_light_off";      //Landing light 04 off.
public const string landing_05_light_off = "sim/lights/landing_05_light_off";      //Landing light 05 off.
public const string landing_06_light_off = "sim/lights/landing_06_light_off";      //Landing light 06 off.
public const string landing_07_light_off = "sim/lights/landing_07_light_off";      //Landing light 07 off.
public const string landing_08_light_off = "sim/lights/landing_08_light_off";      //Landing light 08 off.
public const string landing_09_light_off = "sim/lights/landing_09_light_off";      //Landing light 09 off.
public const string landing_10_light_off = "sim/lights/landing_10_light_off";      //Landing light 10 off.
public const string landing_11_light_off = "sim/lights/landing_11_light_off";      //Landing light 11 off.
public const string landing_12_light_off = "sim/lights/landing_12_light_off";      //Landing light 12 off.
public const string landing_13_light_off = "sim/lights/landing_13_light_off";      //Landing light 13 off.
public const string landing_14_light_off = "sim/lights/landing_14_light_off";      //Landing light 14 off.
public const string landing_15_light_off = "sim/lights/landing_15_light_off";      //Landing light 15 off.
public const string landing_16_light_off = "sim/lights/landing_16_light_off";      //Landing light 16 off.
public const string landing_01_light_tog = "sim/lights/landing_01_light_tog";      //Landing light 01 toggle.
public const string landing_02_light_tog = "sim/lights/landing_02_light_tog";      //Landing light 02 toggle.
public const string landing_03_light_tog = "sim/lights/landing_03_light_tog";      //Landing light 03 toggle.
public const string landing_04_light_tog = "sim/lights/landing_04_light_tog";      //Landing light 04 toggle.
public const string landing_05_light_tog = "sim/lights/landing_05_light_tog";      //Landing light 05 toggle.
public const string landing_06_light_tog = "sim/lights/landing_06_light_tog";      //Landing light 06 toggle.
public const string landing_07_light_tog = "sim/lights/landing_07_light_tog";      //Landing light 07 toggle.
public const string landing_08_light_tog = "sim/lights/landing_08_light_tog";      //Landing light 08 toggle.
public const string landing_09_light_tog = "sim/lights/landing_09_light_tog";      //Landing light 09 toggle.
public const string landing_10_light_tog = "sim/lights/landing_10_light_tog";      //Landing light 10 toggle.
public const string landing_11_light_tog = "sim/lights/landing_11_light_tog";      //Landing light 11 toggle.
public const string landing_12_light_tog = "sim/lights/landing_12_light_tog";      //Landing light 12 toggle.
public const string landing_13_light_tog = "sim/lights/landing_13_light_tog";      //Landing light 13 toggle.
public const string landing_14_light_tog = "sim/lights/landing_14_light_tog";      //Landing light 14 toggle.
public const string landing_15_light_tog = "sim/lights/landing_15_light_tog";      //Landing light 15 toggle.
public const string landing_16_light_tog = "sim/lights/landing_16_light_tog";      //Landing light 16 toggle.
public const string generic_01_light_tog = "sim/lights/generic_01_light_tog";      //Generic light 01 toggle.
public const string generic_02_light_tog = "sim/lights/generic_02_light_tog";      //Generic light 02 toggle.
public const string generic_03_light_tog = "sim/lights/generic_03_light_tog";      //Generic light 03 toggle.
public const string generic_04_light_tog = "sim/lights/generic_04_light_tog";      //Generic light 04 toggle.
public const string generic_05_light_tog = "sim/lights/generic_05_light_tog";      //Generic light 05 toggle.
public const string generic_06_light_tog = "sim/lights/generic_06_light_tog";      //Generic light 06 toggle.
public const string generic_07_light_tog = "sim/lights/generic_07_light_tog";      //Generic light 07 toggle.
public const string generic_08_light_tog = "sim/lights/generic_08_light_tog";      //Generic light 08 toggle.
public const string generic_09_light_tog = "sim/lights/generic_09_light_tog";      //Generic light 09 toggle.
public const string generic_10_light_tog = "sim/lights/generic_10_light_tog";      //Generic light 10 toggle.
public const string generic_11_light_tog = "sim/lights/generic_11_light_tog";      //Generic light 11 toggle.
public const string generic_12_light_tog = "sim/lights/generic_12_light_tog";      //Generic light 12 toggle.
public const string generic_13_light_tog = "sim/lights/generic_13_light_tog";      //Generic light 13 toggle.
public const string generic_14_light_tog = "sim/lights/generic_14_light_tog";      //Generic light 14 toggle.
public const string generic_15_light_tog = "sim/lights/generic_15_light_tog";      //Generic light 15 toggle.
public const string generic_16_light_tog = "sim/lights/generic_16_light_tog";      //Generic light 16 toggle.
public const string generic_17_light_tog = "sim/lights/generic_17_light_tog";      //Generic light 17 toggle.
public const string generic_18_light_tog = "sim/lights/generic_18_light_tog";      //Generic light 18 toggle.
public const string generic_19_light_tog = "sim/lights/generic_19_light_tog";      //Generic light 19 toggle.
public const string generic_20_light_tog = "sim/lights/generic_20_light_tog";      //Generic light 20 toggle.
public const string generic_21_light_tog = "sim/lights/generic_21_light_tog";      //Generic light 21 toggle.
public const string generic_22_light_tog = "sim/lights/generic_22_light_tog";      //Generic light 22 toggle.
public const string generic_23_light_tog = "sim/lights/generic_23_light_tog";      //Generic light 23 toggle.
public const string generic_24_light_tog = "sim/lights/generic_24_light_tog";      //Generic light 24 toggle.
public const string generic_25_light_tog = "sim/lights/generic_25_light_tog";      //Generic light 25 toggle.
public const string generic_26_light_tog = "sim/lights/generic_26_light_tog";      //Generic light 26 toggle.
public const string generic_27_light_tog = "sim/lights/generic_27_light_tog";      //Generic light 27 toggle.
public const string generic_28_light_tog = "sim/lights/generic_28_light_tog";      //Generic light 28 toggle.
public const string generic_29_light_tog = "sim/lights/generic_29_light_tog";      //Generic light 29 toggle.
public const string generic_30_light_tog = "sim/lights/generic_30_light_tog";      //Generic light 30 toggle.
public const string generic_31_light_tog = "sim/lights/generic_31_light_tog";      //Generic light 31 toggle.
public const string generic_32_light_tog = "sim/lights/generic_32_light_tog";      //Generic light 32 toggle.
public const string generic_33_light_tog = "sim/lights/generic_33_light_tog";      //Generic light 33 toggle.
public const string generic_34_light_tog = "sim/lights/generic_34_light_tog";      //Generic light 34 toggle.
public const string generic_35_light_tog = "sim/lights/generic_35_light_tog";      //Generic light 35 toggle.
public const string generic_36_light_tog = "sim/lights/generic_36_light_tog";      //Generic light 36 toggle.
public const string generic_37_light_tog = "sim/lights/generic_37_light_tog";      //Generic light 37 toggle.
public const string generic_38_light_tog = "sim/lights/generic_38_light_tog";      //Generic light 38 toggle.
public const string generic_39_light_tog = "sim/lights/generic_39_light_tog";      //Generic light 39 toggle.
public const string generic_40_light_tog = "sim/lights/generic_40_light_tog";      //Generic light 40 toggle.
public const string generic_41_light_tog = "sim/lights/generic_41_light_tog";      //Generic light 41 toggle.
public const string generic_42_light_tog = "sim/lights/generic_42_light_tog";      //Generic light 42 toggle.
public const string generic_43_light_tog = "sim/lights/generic_43_light_tog";      //Generic light 43 toggle.
public const string generic_44_light_tog = "sim/lights/generic_44_light_tog";      //Generic light 44 toggle.
public const string generic_45_light_tog = "sim/lights/generic_45_light_tog";      //Generic light 45 toggle.
public const string generic_46_light_tog = "sim/lights/generic_46_light_tog";      //Generic light 46 toggle.
public const string generic_47_light_tog = "sim/lights/generic_47_light_tog";      //Generic light 47 toggle.
public const string generic_48_light_tog = "sim/lights/generic_48_light_tog";      //Generic light 48 toggle.
public const string generic_49_light_tog = "sim/lights/generic_49_light_tog";      //Generic light 49 toggle.
public const string generic_50_light_tog = "sim/lights/generic_50_light_tog";      //Generic light 50 toggle.
public const string generic_51_light_tog = "sim/lights/generic_51_light_tog";      //Generic light 51 toggle.
public const string generic_52_light_tog = "sim/lights/generic_52_light_tog";      //Generic light 52 toggle.
public const string generic_53_light_tog = "sim/lights/generic_53_light_tog";      //Generic light 53 toggle.
public const string generic_54_light_tog = "sim/lights/generic_54_light_tog";      //Generic light 54 toggle.
public const string generic_55_light_tog = "sim/lights/generic_55_light_tog";      //Generic light 55 toggle.
public const string generic_56_light_tog = "sim/lights/generic_56_light_tog";      //Generic light 56 toggle.
public const string generic_57_light_tog = "sim/lights/generic_57_light_tog";      //Generic light 57 toggle.
public const string generic_58_light_tog = "sim/lights/generic_58_light_tog";      //Generic light 58 toggle.
public const string generic_59_light_tog = "sim/lights/generic_59_light_tog";      //Generic light 59 toggle.
public const string generic_60_light_tog = "sim/lights/generic_60_light_tog";      //Generic light 60 toggle.
public const string generic_61_light_tog = "sim/lights/generic_61_light_tog";      //Generic light 61 toggle.
public const string generic_62_light_tog = "sim/lights/generic_62_light_tog";      //Generic light 62 toggle.
public const string generic_63_light_tog = "sim/lights/generic_63_light_tog";      //Generic light 63 toggle.
public const string generic_64_light_tog = "sim/lights/generic_64_light_tog";      //Generic light 64 toggle.
public const string spot_lights_on = "sim/lights/spot_lights_on";      //Spot lights on.
public const string spot_lights_off = "sim/lights/spot_lights_off";      //Spot lights off.
public const string spot_lights_toggle = "sim/lights/spot_lights_toggle";      //Spot lights toggle.
public const string spot_light_left = "sim/lights/spot_light_left";           //Aim spotlight left.
public const string spot_light_right = "sim/lights/spot_light_right";           //Aim spotlight right.
public const string spot_light_up = "sim/lights/spot_light_up";           //Aim spotlight up.
public const string spot_light_down = "sim/lights/spot_light_down";           //Aim spotlight down.
public const string spot_light_center = "sim/lights/spot_light_center";           //Aim spotlight to center.