public const string magnetos_off = "sim/magnetos/magnetos_off";                          //Magnetos off.
public const string magnetos_both = "sim/magnetos/magnetos_both";                         //Magnetos both.
public const string magnetos_down_1 = "sim/magnetos/magnetos_down_1";                       //Magnetos down one notch for engine #1.
public const string magnetos_down_2 = "sim/magnetos/magnetos_down_2";                       //Magnetos down one notch for engine #2.
public const string magnetos_down_3 = "sim/magnetos/magnetos_down_3";                       //Magnetos down one notch for engine #3.
public const string magnetos_down_4 = "sim/magnetos/magnetos_down_4";                       //Magnetos down one notch for engine #4.
public const string magnetos_down_5 = "sim/magnetos/magnetos_down_5";                       //Magnetos down one notch for engine #5.
public const string magnetos_down_6 = "sim/magnetos/magnetos_down_6";                       //Magnetos down one notch for engine #6.
public const string magnetos_down_7 = "sim/magnetos/magnetos_down_7";                       //Magnetos down one notch for engine #7.
public const string magnetos_down_8 = "sim/magnetos/magnetos_down_8";                       //Magnetos down one notch for engine #8.
public const string magnetos_up_1 = "sim/magnetos/magnetos_up_1";                         //Magnetos up one notch for engine #1.
public const string magnetos_up_2 = "sim/magnetos/magnetos_up_2";                         //Magnetos up one notch for engine #2.
public const string magnetos_up_3 = "sim/magnetos/magnetos_up_3";                         //Magnetos up one notch for engine #3.
public const string magnetos_up_4 = "sim/magnetos/magnetos_up_4";                         //Magnetos up one notch for engine #4.
public const string magnetos_up_5 = "sim/magnetos/magnetos_up_5";                         //Magnetos up one notch for engine #5.
public const string magnetos_up_6 = "sim/magnetos/magnetos_up_6";                         //Magnetos up one notch for engine #6.
public const string magnetos_up_7 = "sim/magnetos/magnetos_up_7";                         //Magnetos up one notch for engine #7.
public const string magnetos_up_8 = "sim/magnetos/magnetos_up_8";                         //Magnetos up one notch for engine #8.
public const string magnetos_off_1 = "sim/magnetos/magnetos_off_1";                        //Magnetos off for engine #1.
public const string magnetos_off_2 = "sim/magnetos/magnetos_off_2";                        //Magnetos off for engine #2.
public const string magnetos_off_3 = "sim/magnetos/magnetos_off_3";                        //Magnetos off for engine #3.
public const string magnetos_off_4 = "sim/magnetos/magnetos_off_4";                        //Magnetos off for engine #4.
public const string magnetos_off_5 = "sim/magnetos/magnetos_off_5";                        //Magnetos off for engine #5.
public const string magnetos_off_6 = "sim/magnetos/magnetos_off_6";                        //Magnetos off for engine #6.
public const string magnetos_off_7 = "sim/magnetos/magnetos_off_7";                        //Magnetos off for engine #7.
public const string magnetos_off_8 = "sim/magnetos/magnetos_off_8";                        //Magnetos off for engine #8.
public const string magnetos_left_1 = "sim/magnetos/magnetos_left_1";                       //Magnetos left for engine #1.
public const string magnetos_left_2 = "sim/magnetos/magnetos_left_2";                       //Magnetos left for engine #2.
public const string magnetos_left_3 = "sim/magnetos/magnetos_left_3";                       //Magnetos left for engine #3.
public const string magnetos_left_4 = "sim/magnetos/magnetos_left_4";                       //Magnetos left for engine #4.
public const string magnetos_left_5 = "sim/magnetos/magnetos_left_5";                       //Magnetos left for engine #5.
public const string magnetos_left_6 = "sim/magnetos/magnetos_left_6";                       //Magnetos left for engine #6.
public const string magnetos_left_7 = "sim/magnetos/magnetos_left_7";                       //Magnetos left for engine #7.
public const string magnetos_left_8 = "sim/magnetos/magnetos_left_8";                       //Magnetos left for engine #8.
public const string magnetos_right_1 = "string sim/magnetos/magnetos_right_1";                      //Magnetos right for engine #1.
public const string magnetos_right_2 = "string sim/magnetos/magnetos_right_2";                      //Magnetos right for engine #2.
public const string magnetos_right_3 = "string sim/magnetos/magnetos_right_3";                      //Magnetos right for engine #3.
public const string magnetos_right_4 = "string sim/magnetos/magnetos_right_4";                      //Magnetos right for engine #4.
public const string magnetos_right_5 = "string sim/magnetos/magnetos_right_5";                      //Magnetos right for engine #5.
public const string magnetos_right_6 = "string sim/magnetos/magnetos_right_6";                      //Magnetos right for engine #6.
public const string magnetos_right_7 = "string sim/magnetos/magnetos_right_7";                      //Magnetos right for engine #7.
public const string magnetos_right_8 = "string sim/magnetos/magnetos_right_8";                      //Magnetos right for engine #8.
public const string magnetos_both_1 = "sim/magnetos/magnetos_both_1";                       //Magnetos both for engine #1.
public const string magnetos_both_2 = "sim/magnetos/magnetos_both_2";                       //Magnetos both for engine #2.
public const string magnetos_both_3 = "sim/magnetos/magnetos_both_3";                       //Magnetos both for engine #3.
public const string magnetos_both_4 = "sim/magnetos/magnetos_both_4";                       //Magnetos both for engine #4.
public const string magnetos_both_5 = "sim/magnetos/magnetos_both_5";                       //Magnetos both for engine #5.
public const string magnetos_both_6 = "sim/magnetos/magnetos_both_6";                       //Magnetos both for engine #6.
public const string magnetos_both_7 = "sim/magnetos/magnetos_both_7";                       //Magnetos both for engine #7.
public const string magnetos_both_8 = "sim/magnetos/magnetos_both_8";                       //Magnetos both for engine #8.