public const string quit = "sim/operation/quit";                                 //Quit X-Plane.
public const string screenshot = "sim/operation/screenshot";                           //Take a screenshot.
public const string show_menu = "sim/operation/show_menu";                            //Show the in-sim menu.
public const string make_current_aircraft_icons ="sim/operation/make_current_aircraft_icons";          //(Re)generate all icons for the current aircraft.
public const string make_single_icon = "sim/operation/make_single_icon";                     //(Re)generate the icon for the current aircraft & livery.
public const string make_missing_icons = "sim/operation/make_missing_icons";                   //Generate all missing aircraft & livery icons.
public const string regen_weather = "sim/operation/regen_weather";                        //Regenerate weather.
public const string cycle_dump = "sim/operation/cycle_dump";                           //Print out a cycle dump for this frame.
public const string stab_deriv_pitch = "sim/operation/stab_deriv_pitch";                     //Print longitudinal stability derivative.
public const string stab_deriv_heading = "sim/operation/stab_deriv_heading";                   //Print lateral stability derivative.
public const string recording = "sim/operation/recording";                            //Toggle user interaction recording pane.
public const string create_snap_marker = "sim/operation/create_snap_marker";                   //Drop a snapshot marker for replay mode.
public const string test_data_ref = "sim/operation/test_data_ref";                        //Test dataref: Run from 0 to 1 and back.
public const string show_fps = "sim/operation/show_fps";                             //Toggle displaying the simulator's frames per second onscreen.
public const string dev_console  = "sim/operation/dev_console";                          //Toggle dev console.
public const string toggle_full_screen = "sim/operation/toggle_full_screen";                   //Toggle full-screen mode.
public const string reload_aircraftreload_aircraft = "sim/operation/reload_aircraft";                      //Force reloading the current aircraft.
public const string reload_sceneryreload_scenery = "sim/operation/reload_scenery";                       //Force reloading the current scenery.
public const string load_real_weather = "sim/operation/load_real_weather";                    //Scan real weather files.
public const string fail_system = "sim/operation/fail_system";                          //Fail selected in failures screen.
public const string make_panel_previews = "sim/operation/make_panel_previews";                  //Make screenshots of your panels.
public const string close_windows = "sim/operation/close_windows";                        //Close any windows to get back to cockpit.
public const string load_situation_1 = "sim/operation/load_situation_1";                     //Load situation.
public const string load_situation_2 = "sim/operation/load_situation_2";                     //Load situation.
public const string load_situation_3 = "sim/operation/load_situation_3";                     //Load situation.
public const string toggle_flight_config = "sim/operation/toggle_flight_config";                 //Toggle the Flight Configuration window.
public const string toggle_main_menu = "sim/operation/toggle_main_menu";                     //Toggle the Main Menu screen.
public const string toggle_settings_window = "sim/operation/toggle_settings_window";               //Toggle the Settings window.
public const string toggle_flight_school_window = "sim/operation/toggle_flight_school_window";          //Toggle the Flight School window.
public const string toggle_key_shortcuts_window = "sim/operation/toggle_key_shortcuts_window";          //Toggle the Keyboard Shortcuts window.
public const string open_weight_and_balance_window = "sim/operation/open_weight_and_balance_window";       //Open the Weight & Balance window.
public const string open_failures_window = "sim/operation/open_failures_window";                 //Open the Failures window.
public const string toggle_data_output_graph = "sim/operation/toggle_data_output_graph";             //Toggle display of the data output graph.
public const string slider_01 = "sim/operation/slider_01";                            //Slider #1 On/Off control.
public const string slider_02 = "sim/operation/slider_02";                            //Slider #2 On/Off control.
public const string slider_03 = "sim/operation/slider_03";                            //Slider #3 On/Off control.
public const string slider_04 = "sim/operation/slider_04";                            //Slider #4 On/Off control.
public const string slider_05 = "sim/operation/slider_05";                            //Slider #5 On/Off control.
public const string slider_06 = "sim/operation/slider_06";                            //Slider #6 On/Off control.
public const string slider_07 = "sim/operation/slider_07";                            //Slider #7 On/Off control.
public const string slider_08 = "sim/operation/slider_08";                            //Slider #8 On/Off control.
public const string slider_09 = "sim/operation/slider_09";                            //Slider #9 On/Off control.
public const string slider_10 = "sim/operation/slider_10";                            //Slider #10 On/Off control.
public const string slider_11 = "sim/operation/slider_11";                            //Slider #11 On/Off control.
public const string slider_12 = "sim/operation/slider_12";                            //Slider #12 On/Off control.
public const string slider_13 = "sim/operation/slider_13";                            //Slider #13 On/Off control.
public const string slider_14 = "sim/operation/slider_14";                            //Slider #14 On/Off control.
public const string slider_15 = "sim/operation/slider_15";                            //Slider #15 On/Off control.
public const string slider_16 = "sim/operation/slider_16";                            //Slider #16 On/Off control.
public const string slider_17 = "sim/operation/slider_17";                            //Slider #17 On/Off control.
public const string slider_18 = "sim/operation/slider_18";                            //Slider #18 On/Off control.
public const string slider_19 = "sim/operation/slider_19";                            //Slider #19 On/Off control.
public const string slider_20 = "sim/operation/slider_20";                            //Slider #20 On/Off control.
public const string slider_21 = "sim/operation/slider_21";                            //Slider #21 On/Off control.
public const string slider_22 = "sim/operation/slider_22";                            //Slider #22 On/Off control.
public const string slider_23 = "sim/operation/slider_23";                            //Slider #23 On/Off control.
public const string slider_24 = "sim/operation/slider_24";                            //Slider #24 On/Off control.
public const string fix_all_systems = "sim/operation/fix_all_systems";                      //Fix all failed systems.
public const string auto_board = "sim/operation/auto_board";                           //Auto-set electrical system for boarding.
public const string auto_start = "sim/operation/auto_start";                           //Auto-start engines to running, real-time.
public const string quick_start = "sim/operation/quick_start";                          //Quick start engines to running, instant.
public const string prev_livery = "sim/operation/prev_livery";           //Load previous livery.
public const string next_livery = "sim/operation/next_livery";           //Load next livery.
public const string ground_speed_change = "sim/operation/ground_speed_change";           //Sim 1x 2x 4x ground speed.
public const string freeze_toggle = "sim/operation/freeze_toggle";           //Freeze the groundspeed of the simulation.
public const string time_down = "sim/operation/time_down";           //Time: a little earlier.
public const string time_up = "sim/operation/time_up";           //Time: a little later.
public const string time_down_lots = "sim/operation/time_down_lots";           //Time: a lot earlier.
public const string time_up_lots = "sim/operation/time_up_lots";           //Time: a lot later.
public const string date_down = "sim/operation/date_down";           //Date: a little earlier.
public const string date_up = "sim/operation/date_up";           //Date: a little later.
public const string flightmodel_speed_change = "sim/operation/flightmodel_speed_change";           //Sim 1x 2x 4x sim speed.
public const string pause_toggle = "sim/operation/pause_toggle";           //Pause the simulation.
public const string video_record_toggle = "sim/operation/video_record_toggle";           //Toggle AVI movie recording.
public const string configure_video_recording = "sim/operation/configure_video_recording";           //Configure AVI movie recording.
public const string toggle_logbook = "sim/operation/toggle_logbook";           //Toggle logbook window.
public const string save_flight = "sim/operation/save_flight";           //Toggle Save Flight window.
public const string load_flight = "sim/operation/load_flight";           //Toggle Load Flight window.
public const string text_file_toggle = "sim/operation/text_file_toggle";           //Toggle text file.
public const string checklist_toggle = "sim/operation/checklist_toggle";           //Toggle checklist.
public const string checklist_next = "sim/operation/checklist_next";           //Next item in checklist.
public const string checklist_previous = "sim/operation/checklist_previous";           //Previous item in checklist.
public const string contact_atc = "sim/operation/contact_atc";           //Contact ATC.
public const string toggle_ai_flies = "sim/operation/toggle_ai_flies";           //Toggle AI flying your aircraft.
public const string toggle_yoke = "sim/operation/toggle_yoke";           //Toggle yoke visibility.
public const string reset_flight = "sim/operation/reset_flight";           //Reset flight to most recent start.
public const string go_to_default = "sim/operation/go_to_default";           //Reset flight to nearest airport.
public const string reset_to_runway = "sim/operation/reset_to_runway";           //Reset flight to nearest runway.
public const string Grass_Field_Takeoff = "sim/operation/Grass_Field_Takeoff";           //Grass field takeoff.
public const string Dirt_Field_Takeoff = "sim/operation/Dirt_Field_Takeoff";           //Dirt field takeoff.
public const string Gravel_Field_Takeoff = "sim/operation/Gravel_Field_Takeoff";           //Gravel field takeoff.
public const string Water_Way_Takeoff = "sim/operation/Water_Way_Takeoff";           //Waterway takeoff.
public const string Helipad_Takeoff = "sim/operation/Helipad_Takeoff";           //Helipad takeoff.
public const string Carrier_Catshot = "sim/operation/Carrier_Catshot";           //Carrier catshot.
public const string Glider_Winch = "sim/operation/Glider_Winch";           //Glider winch start.
public const string Glider_Tow = "sim/operation/Glider_Tow";           //Glider tow start.
public const string Air_Drop_from_B_52 = "sim/operation/Air_Drop_from_B_52";           //Airdrop from B-52.
public const string start_carried = "sim/operation/start_carried";           //Other aircraft carries your own.
public const string Piggyback_Shuttle_on_747 = "sim/operation/Piggyback_Shuttle_on_747";           //Piggyback Shuttle on 747.
public const string carry_other_aircraft = "sim/operation/carry_other_aircraft";           //Carry another aircraft.
public const string Formation_Flying = "sim/operation/Formation_Flying";           //Formation flying.
public const string Air_Refuel_Boom = "sim/operation/Air_Refuel_Boom";           //Air refueling (boom).
public const string Air_Refuel_Basket = "sim/operation/Air_Refuel_Basket";           //Air refueling (basket).
public const string Aircraft_Carrier_Approach = "sim/operation/Aircraft_Carrier_Approach";           //Aircraft carrier approach.
public const string Frigate_Approach = "sim/operation/Frigate_Approach";           //Frigate approach.
public const string Medium_Oil_Rig_Approach = "sim/operation/Medium_Oil_Rig_Approach";           //Medium oil rig approach.
public const string Large_Oil_Platform_Approach = "sim/operation/Large_Oil_Platform_Approach";           //Large oil platform approach.
public const string Forest_Fire_Approach = "sim/operation/Forest_Fire_Approach";           //Forest fire approach.
public const string Space_Shuttle_Full_Re_entry = "sim/operation/Space_Shuttle_Full_Re_entry";           //Space Shuttle: Full re-entry.
public const string Space_Shuttle_Final_Re_entry = "sim/operation/Space_Shuttle_Final_Re_entry";           //Space Shuttle: Final re-entry.
public const string Space_Shuttle_Full_Approach = "sim/operation/Space_Shuttle_Full_Approach";           //Space Shuttle: Full approach.
public const string Space_Shuttle_Final_Approach = "sim/operation/Space_Shuttle_Final_Approach";           //Space Shuttle: Final approach.
public const string toggle_sky_colors_win = "sim/operation/toggle_sky_colors_win";           //Toggle the sky colors window.