public const string power_nav1_off = "sim/radios/power_nav1_off";           //Power NAV1 off.
public const string power_nav1_on = "sim/radios/power_nav1_on";           //Power NAV1 on.
public const string power_nav2_off = "sim/radios/power_nav2_off";           //Power NAV2 off.
public const string power_nav2_on = "sim/radios/power_nav2_on";           //Power NAV2 on.
public const string power_com1_off = "sim/radios/power_com1_off";           //Power COM1 off.
public const string power_com1_on = "sim/radios/power_com1_on";           //Power COM1 on.
public const string power_com2_off = "sim/radios/power_com2_off";           //Power COM2 off.
public const string power_com2_on = "sim/radios/power_com2_on";           //Power COM2 on.
public const string power_adf1_dn = "sim/radios/power_adf1_dn";           //Power ADF1 dn.
public const string power_adf1_up = "sim/radios/power_adf1_up";           //Power ADF1 up.
public const string power_adf2_dn = "sim/radios/power_adf2_dn";           //Power ADF2 dn.
public const string power_adf2_up = "sim/radios/power_adf2_up";           //Power ADF2 up.
public const string adf1_power_mode_0 = "sim/radios/adf1_power_mode_0";           //ADF 1 off.
public const string adf1_power_mode_1 = "sim/radios/adf1_power_mode_1";           //ADF 1 antenna.
public const string adf1_power_mode_2 = "sim/radios/adf1_power_mode_2";           //ADF 1 on.
public const string adf1_power_mode_3 = "sim/radios/adf1_power_mode_3";           //ADF 1 tone.
public const string adf1_power_mode_4 = "sim/radios/adf1_power_mode_4";           //ADF 1 test.
public const string adf2_power_mode_0 = "sim/radios/adf2_power_mode_0";           //ADF 2 off.
public const string adf2_power_mode_1 = "sim/radios/adf2_power_mode_1";           //ADF 2 antenna.
public const string adf2_power_mode_2 = "sim/radios/adf2_power_mode_2";           //ADF 2 on.
public const string adf2_power_mode_3 = "sim/radios/adf2_power_mode_3";           //ADF 2 tone.
public const string adf2_power_mode_4 = "sim/radios/adf2_power_mode_4";           //ADF 2 test.
public const string actv_com1_coarse_down = "sim/radios/actv_com1_coarse_down";           //COM 1 coarse down.
public const string actv_com1_coarse_up = "sim/radios/actv_com1_coarse_up";           //COM 1 coarse up.
public const string actv_com1_fine_down = "sim/radios/actv_com1_fine_down";           //COM 1 fine down (25kHz).
public const string actv_com1_fine_up = "sim/radios/actv_com1_fine_up";           //COM 1 fine up (25kHz).
public const string actv_com1_fine_down_833 = "sim/radios/actv_com1_fine_down_833";           //COM 1 fine down (8.33 kHz).
public const string actv_com1_fine_up_833 = "sim/radios/actv_com1_fine_up_833";           //COM 1 fine up (8.33 kHz).
public const string stby_com1_coarse_down = "sim/radios/stby_com1_coarse_down";           //COM 1 standby coarse down.
public const string stby_com1_coarse_up = "sim/radios/stby_com1_coarse_up";           //COM 1 standby coarse up.
public const string stby_com1_fine_down = "sim/radios/stby_com1_fine_down";           //COM 1 standby fine down (25kHz).
public const string stby_com1_fine_up = "sim/radios/stby_com1_fine_up";           //COM 1 standby fine up (25kHz).
public const string stby_com1_fine_down_833 = "sim/radios/stby_com1_fine_down_833";           //COM 1 standby fine down (8.33kHz).
public const string stby_com1_fine_up_833 = "sim/radios/stby_com1_fine_up_833";           //COM 1 standby fine up (8.33kHz).
public const string actv_com2_coarse_down = "sim/radios/actv_com2_coarse_down";           //COM 2 coarse down.
public const string actv_com2_coarse_up = "sim/radios/actv_com2_coarse_up";           //COM 2 coarse up.
public const string actv_com2_fine_down = "sim/radios/actv_com2_fine_down";           //COM 2 fine down (25kHz).
public const string actv_com2_fine_up = "sim/radios/actv_com2_fine_up";           //COM 2 fine up (25kHz).
public const string actv_com2_fine_down_833 = "sim/radios/actv_com2_fine_down_833";           //COM 2 fine down (8.33kHz).
public const string actv_com2_fine_up_833 = "sim/radios/actv_com2_fine_up_833";           //COM 2 fine up (8.33kHz).
public const string stby_com2_coarse_down = "sim/radios/stby_com2_coarse_down";           //COM 2 standby coarse down.
public const string stby_com2_coarse_up = "sim/radios/stby_com2_coarse_up";           //COM 2 standby coarse up.
public const string stby_com2_fine_down = "sim/radios/stby_com2_fine_down";           //COM 2 standby fine down (25kHz).
public const string stby_com2_fine_up = "sim/radios/stby_com2_fine_up";           //COM 2 standby fine up (25kHz).
public const string stby_com2_fine_down_833 = "sim/radios/stby_com2_fine_down_833";           //COM 2 standby fine down (8.33kHz).
public const string stby_com2_fine_up_833 = "sim/radios/stby_com2_fine_up_833";           //COM 2 standby fine up (8.33kHz).
public const string actv_nav1_coarse_down = "sim/radios/actv_nav1_coarse_down";           //NAV 1 coarse down.
public const string actv_nav1_coarse_up = "sim/radios/actv_nav1_coarse_up";           //NAV 1 coarse up.
public const string actv_nav1_fine_down = "sim/radios/actv_nav1_fine_down";           //NAV 1 fine down.
public const string actv_nav1_fine_up = "sim/radios/actv_nav1_fine_up";           //NAV 1 fine up.
public const string stby_nav1_coarse_down = "sim/radios/stby_nav1_coarse_down";           //NAV 1 standby coarse down.
public const string stby_nav1_coarse_up = "sim/radios/stby_nav1_coarse_up";           //NAV 1 standby coarse up.
public const string stby_nav1_fine_down = "sim/radios/stby_nav1_fine_down";           //NAV 1 standby fine down.
public const string stby_nav1_fine_up = "sim/radios/stby_nav1_fine_up";           //NAV 1 standby fine up.
public const string actv_nav2_coarse_down = "sim/radios/actv_nav2_coarse_down";           //NAV 2 coarse down.
public const string actv_nav2_coarse_up = "sim/radios/actv_nav2_coarse_up";           //NAV 2 coarse up.
public const string actv_nav2_fine_down = "sim/radios/actv_nav2_fine_down";           //NAV 2 fine down.
public const string actv_nav2_fine_up = "sim/radios/actv_nav2_fine_up";           //NAV 2 fine up.
public const string stby_nav2_coarse_down = "sim/radios/stby_nav2_coarse_down";           //NAV 2 standby coarse down.
public const string stby_nav2_coarse_up = "sim/radios/stby_nav2_coarse_up";           //NAV 2 standby coarse up.
public const string stby_nav2_fine_down = "sim/radios/stby_nav2_fine_down";           //NAV 2 standby fine down.
public const string stby_nav2_fine_up = "sim/radios/stby_nav2_fine_up";           //NAV 2 standby fine up.
public const string actv_dme_coarse_down = "sim/radios/actv_dme_coarse_down";           //DME coarse down.
public const string actv_dme_coarse_up = "sim/radios/actv_dme_coarse_up";           //DME coarse up.
public const string actv_dme_fine_down = "sim/radios/actv_dme_fine_down";           //DME fine down.
public const string actv_dme_fine_up = "sim/radios/actv_dme_fine_up";           //DME fine up.
public const string stby_dme_coarse_down = "sim/radios/stby_dme_coarse_down";           //DME standby coarse down.
public const string stby_dme_coarse_up = "sim/radios/stby_dme_coarse_up";           //DME standby coarse up.
public const string stby_dme_fine_down = "sim/radios/stby_dme_fine_down";           //DME standby fine down.
public const string stby_dme_fine_up = "sim/radios/stby_dme_fine_up";           //DME standby fine up.
public const string actv_adf1_hundreds_down = "sim/radios/actv_adf1_hundreds_down";           //ADF active 1 hundreds down.
public const string actv_adf1_hundreds_up = "sim/radios/actv_adf1_hundreds_up";           //ADF active 1 hundreds up.
public const string actv_adf1_tens_down = "sim/radios/actv_adf1_tens_down";           //ADF active 1 tens down.
public const string actv_adf1_tens_up = "sim/radios/actv_adf1_tens_up";           //ADF active 1 tens up.
public const string actv_adf1_ones_down = "sim/radios/actv_adf1_ones_down";           //ADF active 1 ones down.
public const string actv_adf1_ones_up = "sim/radios/actv_adf1_ones_up";           //ADF active 1 ones up.
public const string actv_adf1_ones_tens_down = "sim/radios/actv_adf1_ones_tens_down";           //ADF active 1 ones and tens down.
public const string actv_adf1_ones_tens_up = "sim/radios/actv_adf1_ones_tens_up";           //ADF active 1 ones and tens up.
public const string actv_adf1_hundreds_thous_down = "sim/radios/actv_adf1_hundreds_thous_down";           //ADF active 1 hundreds and thousands down.
public const string actv_adf1_hundreds_thous_up = "sim/radios/actv_adf1_hundreds_thous_up";           //ADF active 1 hundreds and thousands up.
public const string stby_adf1_hundreds_down = "sim/radios/stby_adf1_hundreds_down";           //ADF standby 1 hundreds down.
public const string stby_adf1_hundreds_up = "sim/radios/stby_adf1_hundreds_up";           //ADF standby 1 hundreds up.
public const string stby_adf1_tens_down = "sim/radios/stby_adf1_tens_down";           //ADF standby 1 tens down.
public const string stby_adf1_tens_up = "sim/radios/stby_adf1_tens_up";           //ADF standby 1 tens up.
public const string stby_adf1_ones_down = "sim/radios/stby_adf1_ones_down";           //ADF standby 1 ones down.
public const string stby_adf1_ones_up = "sim/radios/stby_adf1_ones_up";           //ADF standby 1 ones up.
public const string stby_adf1_ones_tens_down = "sim/radios/stby_adf1_ones_tens_down";           //ADF standby 1 ones and tens down.
public const string stby_adf1_ones_tens_up = "sim/radios/stby_adf1_ones_tens_up";           //ADF standby 1 ones and tens up.
public const string stby_adf1_hundreds_thous_down = "sim/radios/stby_adf1_hundreds_thous_down";           //ADF standby 1 hundreds and thousands down.
public const string stby_adf1_hundreds_thous_up = "sim/radios/stby_adf1_hundreds_thous_up";           //ADF standby 1 hundreds and thousands up.
public const string actv_adf2_hundreds_down = "sim/radios/actv_adf2_hundreds_down";           //ADF active 2 hundreds down.
public const string actv_adf2_hundreds_up = "sim/radios/actv_adf2_hundreds_up";           //ADF active 2 hundreds up.
public const string actv_adf2_tens_down = "sim/radios/actv_adf2_tens_down";           //ADF active 2 tens down.
public const string actv_adf2_tens_up = "sim/radios/actv_adf2_tens_up";           //ADF active 2 tens up.
public const string actv_adf2_ones_down = "sim/radios/actv_adf2_ones_down";           //ADF active 2 ones down.
public const string actv_adf2_ones_up = "sim/radios/actv_adf2_ones_up";           //ADF active 2 ones up.
public const string actv_adf2_ones_tens_down = "sim/radios/actv_adf2_ones_tens_down";           //ADF active 2 ones and tens down.
public const string actv_adf2_ones_tens_up = "sim/radios/actv_adf2_ones_tens_up";           //ADF active 2 ones and tens up.
public const string actv_adf2_hundreds_thous_down = "sim/radios/actv_adf2_hundreds_thous_down";           //ADF active 2 hundreds and thousands down.
public const string actv_adf2_hundreds_thous_up = "sim/radios/actv_adf2_hundreds_thous_up";           //ADF active 2 hundreds and thousands up.
public const string stby_adf2_hundreds_down = "sim/radios/stby_adf2_hundreds_down";           //ADF standby 2 hundreds down.
public const string stby_adf2_hundreds_up = "sim/radios/stby_adf2_hundreds_up";           //ADF standby 2 hundreds up.
public const string stby_adf2_tens_down = "sim/radios/stby_adf2_tens_down";           //ADF standby 2 tens down.
public const string stby_adf2_tens_up = "sim/radios/stby_adf2_tens_up";           //ADF standby 2 tens up.
public const string stby_adf2_ones_down = "sim/radios/stby_adf2_ones_down";           //ADF standby 2 ones down.
public const string stby_adf2_ones_up = "sim/radios/stby_adf2_ones_up";           //ADF standby 2 ones up.
public const string stby_adf2_ones_tens_down = "sim/radios/stby_adf2_ones_tens_down";           //ADF standby 2 ones and tens down.
public const string stby_adf2_ones_tens_up = "sim/radios/stby_adf2_ones_tens_up";           //ADF standby 2 ones and tens up.
public const string stby_adf2_hundreds_thous_down = "sim/radios/stby_adf2_hundreds_thous_down";           //ADF standby 2 hundreds and thousands down.
public const string stby_adf2_hundreds_thous_up = "sim/radios/stby_adf2_hundreds_thous_up";           //ADF standby 2 hundreds and thousands up.
public const string nav1_standy_flip = "sim/radios/nav1_standy_flip";           //NAV 1 flip standby.
public const string nav2_standy_flip = "sim/radios/nav2_standy_flip";           //NAV 2 flip standby.
public const string com1_standy_flip = "sim/radios/com1_standy_flip";           //COM 1 flip standby.
public const string com2_standy_flip = "sim/radios/com2_standy_flip";           //COM 2 flip standby.
public const string adf1_standy_flip = "sim/radios/adf1_standy_flip";           //ADF 1 flip standby.
public const string adf2_standy_flip = "sim/radios/adf2_standy_flip";           //ADF 2 flip standby.
public const string dme_standby_flip = "sim/radios/dme_standby_flip";           //DME flip standby.
public const string RMI_L_tog = "sim/radios/RMI_L_tog";           //RMI left NAV toggle VOR/NDB.
public const string RMI_R_tog = "sim/radios/RMI_R_tog";           //RMI right NAV toggle VOR/NDB.
public const string copilot_RMI_L_tog_cop = "sim/radios/copilot_RMI_L_tog_cop";           //Copilot RMI left NAV toggle VOR/NDB.
public const string copilot_RMI_R_tog_cop = "sim/radios/copilot_RMI_R_tog_cop";           //Copilot RMI right NAV toggle VOR/NDB.
public const string obs1_down = "sim/radios/obs1_down";           //OBS 1 down.
public const string obs1_up = "sim/radios/obs1_up";           //OBS 1 up.
public const string obs2_down = "sim/radios/obs2_down";           //OBS 2 down.
public const string obs2_up = "sim/radios/obs2_up";           //OBS 2 up.
public const string obs_HSI_down = "sim/radios/obs_HSI_down";           //OBS HSI down.
public const string obs_HSI_up = "sim/radios/obs_HSI_up";           //OBS HSI up.
public const string adf1_card_down = "sim/radios/adf1_card_down";           //ADF card 1 down.
public const string adf1_card_up = "sim/radios/adf1_card_up";           //ADF card 1 up.
public const string adf2_card_down = "sim/radios/adf2_card_down";           //ADF card 2 down.
public const string adf2_card_up = "sim/radios/adf2_card_up";           //ADF card 2 up.
public const string copilot_obs1_down = "sim/radios/copilot_obs1_down";           //Copilot OBS 1 down.
public const string copilot_obs1_up = "sim/radios/copilot_obs1_up";           //Copilot OBS 1 up.
public const string copilot_obs2_down = "sim/radios/copilot_obs2_down";           //Copilot OBS 2 down.
public const string copilot_obs2_up = "sim/radios/copilot_obs2_up";           //Copilot OBS 2 up.
public const string copilot_obs_HSI_down = "sim/radios/copilot_obs_HSI_down";           //Copilot OBS HSI down.
public const string copilot_obs_HSI_up = "sim/radios/copilot_obs_HSI_up";           //Copilot OBS HSI up.
public const string copilot_adf1_card_down = "sim/radios/copilot_adf1_card_down";           //Copilot ADF card 1 down.
public const string copilot_adf1_card_up = "sim/radios/copilot_adf1_card_up";           //Copilot ADF card 1 up.
public const string copilot_adf2_card_down = "sim/radios/copilot_adf2_card_down";           //Copilot ADF card 2 down.
public const string copilot_adf2_card_up = "sim/radios/copilot_adf2_card_up";           //Copilot ADF card 2 up.