public const string shut_down = "sim/starters/shut_down";                             //Pull fuel and mags for shutdown.
public const string engage_starter_1 = "sim/starters/engage_starter_1";                      //Engage starter #1.
public const string engage_starter_2 = "sim/starters/engage_starter_2";                      //Engage starter #2.
public const string engage_starter_3 = "sim/starters/engage_starter_3";                      //Engage starter #3.
public const string engage_starter_4 = "sim/starters/engage_starter_4";                      //Engage starter #4.
public const string engage_starter_5 = "sim/starters/engage_starter_5";                      //Engage starter #5.
public const string engage_starter_6 = "sim/starters/engage_starter_6";                      //Engage starter #6.
public const string engage_starter_7 = "sim/starters/engage_starter_7";                      //Engage starter #7.
public const string engage_starter_8 = "sim/starters/engage_starter_8";                      //Engage starter #8.
public const string shut_down_1 = "sim/starters/shut_down_1";                           //Pull fuel and mags for shut-down #1.
public const string shut_down_2 = "sim/starters/shut_down_2";                           //Pull fuel and mags for shut-down #2.
public const string shut_down_3 = "sim/starters/shut_down_3";                           //Pull fuel and mags for shut-down #3.
public const string shut_down_4 = "sim/starters/shut_down_4";                           //Pull fuel and mags for shut-down #4.
public const string shut_down_5 = "sim/starters/shut_down_5";                           //Pull fuel and mags for shut-down #5.
public const string shut_down_6 = "sim/starters/shut_down_6";                           //Pull fuel and mags for shut-down #6.
public const string shut_down_7 = "sim/starters/shut_down_7";                           //Pull fuel and mags for shut-down #7.
public const string shut_down_8 = "sim/starters/shut_down_8";                           //Pull fuel and mags for shut-down #8.