public const string yaw_damper_on = "sim/systems/yaw_damper_on";                          //Yaw damper on.
public const string yaw_damper_off = "sim/systems/yaw_damper_off";                         //Yaw damper off.
public const string yaw_damper_toggle = "sim/systems/yaw_damper_toggle";                      //Toggle yaw damper.
public const string prop_sync_on = "sim/systems/prop_sync_on";                           //Prop sync on.
public const string prop_sync_off = "sim/systems/prop_sync_off";                          //Prop sync off.
public const string prop_sync_toggle = "sim/systems/prop_sync_toggle";                       //Prop sync toggle.
public const string feather_mode_down = "sim/systems/feather_mode_down";                      //Auto-feather mode down.
public const string feather_mode_up = "sim/systems/feather_mode_up";                        //Auto-feather mode up.
public const string feather_mode_off = "sim/systems/feather_mode_off";                       //Auto-feather off.
public const string feather_mode_arm = "sim/systems/feather_mode_arm";                       //Auto-feather on.
public const string feather_mode_test = "sim/systems/feather_mode_test";                      //Auto-feather test.
public const string artificial_stability_toggle = "sim/systems/artificial_stability_toggle";            //Toggle artificial stability power.
public const string avionics_on = "sim/systems/avionics_on";      //Avionics on.
public const string avionics_off = "sim/systems/avionics_off";      //Avionics off.
public const string avionics_toggle = "sim/systems/avionics_toggle";      //Avionics toggle.
public const string seatbelt_sign_toggle = "sim/systems/seatbelt_sign_toggle";           //Toggle seatbelt sign.
public const string no_smoking_toggle = "sim/systems/no_smoking_toggle";           //Toggle smoking sign.
public const string wipers_dn = "sim/systems/wipers_dn";           //Windshield wipers down.
public const string wipers_up = "sim/systems/wipers_up";           //Windshield wipers up.
public const string total_energy_audio_toggle = "sim/systems/total_energy_audio_toggle";           //Toggle total-energy audio.
public const string pre_rotate_toggle = "sim/systems/pre_rotate_toggle";           //Toggle pre-rotate.
public const string overspeed_test = "sim/systems/overspeed_test";           //Prop overspeed test.