public const string transponder_digit_0 = "sim/transponder/transponder_digit_0";           //Transponder digit to 0.
public const string transponder_digit_1 = "sim/transponder/transponder_digit_1";           //Transponder digit to 1.
public const string transponder_digit_2 = "sim/transponder/transponder_digit_2";           //Transponder digit to 2.
public const string transponder_digit_3 = "sim/transponder/transponder_digit_3";           //Transponder digit to 3.
public const string transponder_digit_4 = "sim/transponder/transponder_digit_4";           //Transponder digit to 4.
public const string transponder_digit_5 = "sim/transponder/transponder_digit_5";           //Transponder digit to 5.
public const string transponder_digit_6 = "sim/transponder/transponder_digit_6";           //Transponder digit to 6.
public const string transponder_digit_7 = "sim/transponder/transponder_digit_7";           //Transponder digit to 7.
public const string transponder_CLR = "sim/transponder/transponder_CLR";           //Transponder reset to first digit.
public const string transponder_thousands_down = "sim/transponder/transponder_thousands_down";           //Transponder thousands down.
public const string transponder_thousands_up = "sim/transponder/transponder_thousands_up";           //Transponder thousands up.
public const string transponder_hundreds_down = "sim/transponder/transponder_hundreds_down";           //Transponder hundreds down.
public const string transponder_hundreds_up = "sim/transponder/transponder_hundreds_up";           //Transponder hundreds up.
public const string transponder_tens_down = "sim/transponder/transponder_tens_down";           //Transponder tens down.
public const string transponder_tens_up = "sim/transponder/transponder_tens_up";           //Transponder tens up.
public const string transponder_ones_down = "sim/transponder/transponder_ones_down";           //Transponder ones down.
public const string transponder_ones_up = "sim/transponder/transponder_ones_up";           //Transponder ones up.
public const string transponder_12_down = "sim/transponder/transponder_12_down";           //Transponder digits 1 and 2 down.
public const string transponder_12_up = "sim/transponder/transponder_12_up";           //Transponder digits 1 and 2 up.
public const string transponder_34_down = "sim/transponder/transponder_34_down";           //Transponder digits 3 and 4 down.
public const string transponder_34_up = "sim/transponder/transponder_34_up";           //Transponder digits 3 and 4 up.
public const string transponder_ident = "sim/transponder/transponder_ident";           //Transponder ID.
public const string transponder_off = "sim/transponder/transponder_off";           //Transponder off.
public const string transponder_standby = "sim/transponder/transponder_standby";           //Transponder standby.
public const string transponder_on = "sim/transponder/transponder_on";           //Transponder on.
public const string transponder_alt = "sim/transponder/transponder_alt";           //Transponder alt.
public const string transponder_test = "sim/transponder/transponder_test";           //Transponder test.
public const string transponder_ground = "sim/transponder/transponder_ground";           //Transponder ground.
public const string transponder_dn = "sim/transponder/transponder_dn";           //Transponder mode down.
public const string transponder_up = "sim/transponder/transponder_up";           //Transponder mode up.