public const string track-ir_toggle = "sim/view/track-ir_toggle";                           //Toggle TrackIR control.
public const string ai_controls_views = "sim/view/ai_controls_views";           //Toggle AI controls your views.
public const string free_camera = "sim/view/free_camera";           //Free camera.
public const string default_view = "sim/view/default_view";           //Default view.
public const string forward_with_2d_panel = "sim/view/forward_with_2d_panel";           //Forward with 2-D panel.
public const string forward_with_hud = "sim/view/forward_with_hud";           //Forward with HUD.
public const string forward_with_nothing = "sim/view/forward_with_nothing";           //Forward with nothing.
public const string linear_spot = "sim/view/linear_spot";           //Linear spot.
public const string still_spot = "sim/view/still_spot";           //Still spot.
public const string runway = "sim/view/runway";           //Runway.
public const string circle = "sim/view/circle";           //Circle.
public const string tower = "sim/view/tower";           //Tower.
public const string ridealong = "sim/view/ridealong";           //Ride-along.
public const string track_weapon = "sim/view/track_weapon";           //Track weapon.
public const string chase = "sim/view/chase";           //Chase.
public const string 3d_cockpit_cmnd_look = "sim/view/3d_cockpit_cmnd_look";           //3-D cockpit.
public const string 3d_cockpit_toggle = "sim/view/3d_cockpit_toggle";           //Toggle between 2-D and 3-D cockpit.
public const string lock_geo = "sim/view/lock_geo";           //Lock onto current location.
public const string cinema_verite = "sim/view/cinema_verite";           //Cinema verite.
public const string sunglasses = "sim/view/sunglasses";           //Sunglasses.
public const string night_vision = "sim/view/night_vision";           //Night vision.
public const string flashlight_red = "sim/view/flashlight_red";           //Toggle the red flashlight.
public const string flashlight_wht = "sim/view/flashlight_wht";           //Toggle the white flashlight.
public const string glance_left = "sim/view/glance_left";           //Glance left.
public const string glance_right = "sim/view/glance_right";           //Glance right.
public const string up_left = "sim/view/up_left";           //Glance up and left.
public const string up_right = "sim/view/up_right";           //Glance up and right.
public const string straight_up = "sim/view/straight_up";           //Glance straight up.
public const string straight_down = "sim/view/straight_down";           //Glance straight down.
public const string left_45 = "sim/view/left_45";           //Glance 45 degrees left.
public const string right_45 = "sim/view/right_45";           //Glance 45 degrees right.
public const string left_90 = "sim/view/left_90";           //Glance 90 degrees left.
public const string right_90 = "sim/view/right_90";           //Glance 90 degrees right.
public const string left_135 = "sim/view/left_135";           //Glance 135 degrees left.
public const string right_135 = "sim/view/right_135";           //Glance 135 degrees right.
public const string back = "sim/view/back";           //Glance backward.
public const string 3d_path_toggle = "sim/view/3d_path_toggle";           //3-D path toggle.
public const string 3d_path_reset = "sim/view/3d_path_reset";           //3-D path reset.
public const string show_physics_model = "sim/view/show_physics_model";           //Toggle physics model visualization.
public const string mouse_click_regions_toggle = "sim/view/mouse_click_regions_toggle";           //Toggle visualization of clickable cockpit areas.
public const string instrument_descriptions_toggle = "sim/view/instrument_descriptions_toggle";           //Toggle instrument descriptions on hover.
public const string quick_look_0 = "sim/view/quick_look_0";           //Go to save 3-D cockpit location #1.
public const string quick_look_1 = "sim/view/quick_look_1";           //Go to save 3-D cockpit location #2.
public const string quick_look_2 = "sim/view/quick_look_2";           //Go to save 3-D cockpit location #3.
public const string quick_look_3 = "sim/view/quick_look_3";           //Go to save 3-D cockpit location #4.
public const string quick_look_4 = "sim/view/quick_look_4";           //Go to save 3-D cockpit location #5.
public const string quick_look_5 = "sim/view/quick_look_5";           //Go to save 3-D cockpit location #6.
public const string quick_look_6 = "sim/view/quick_look_6";           //Go to save 3-D cockpit location #7.
public const string quick_look_7 = "sim/view/quick_look_7";           //Go to save 3-D cockpit location #8.
public const string quick_look_8 = "sim/view/quick_look_8";           //Go to save 3-D cockpit location #9.
public const string quick_look_9 = "sim/view/quick_look_9";           //Go to save 3-D cockpit location #10.
public const string quick_look_0_mem = "sim/view/quick_look_0_mem";           //Memorize 3-D cockpit location #1.
public const string quick_look_1_mem = "sim/view/quick_look_1_mem";           //Memorize 3-D cockpit location #2.
public const string quick_look_2_mem = "sim/view/quick_look_2_mem";           //Memorize 3-D cockpit location #3.
public const string quick_look_3_mem = "sim/view/quick_look_3_mem";           //Memorize 3-D cockpit location #4.
public const string quick_look_4_mem = "sim/view/quick_look_4_mem";           //Memorize 3-D cockpit location #5.
public const string quick_look_5_mem = "sim/view/quick_look_5_mem";           //Memorize 3-D cockpit location #6.
public const string quick_look_6_mem = "sim/view/quick_look_6_mem";           //Memorize 3-D cockpit location #7.
public const string quick_look_7_mem = "sim/view/quick_look_7_mem";           //Memorize 3-D cockpit location #8.
public const string quick_look_8_mem = "sim/view/quick_look_8_mem";           //Memorize 3-D cockpit location #9.
public const string quick_look_9_mem = "sim/view/quick_look_9_mem";           //Memorize 3-D cockpit location #10.