public const string re_arm_aircraft = "sim/weapons/re_arm_aircraft";           //Re-arm aircraft to default specs.
public const string master_arm_on = "sim/weapons/master_arm_on";           //Master arm on.
public const string master_arm_off = "sim/weapons/master_arm_off";           //Master arm off.
public const string fire_mode_down = "sim/weapons/fire_mode_down";           //Weapon single/pair/ripple/salvo down.
public const string fire_mode_up = "sim/weapons/fire_mode_up";           //Weapon single/pair/ripple/salvo up.
public const string fire_rate_down = "sim/weapons/fire_rate_down";           //Weapon fire rate down.
public const string fire_rate_up = "sim/weapons/fire_rate_up";           //Weapon fire rate up.
public const string weapon_select_down = "sim/weapons/weapon_select_down";           //Weapon select down.
public const string weapon_select_up = "sim/weapons/weapon_select_up";           //Weapon select up.
public const string fire_guns = "sim/weapons/fire_guns";           //Fire guns.
public const string fire_air_to_air = "sim/weapons/fire_air_to_air";           //Fire air-to-air selection.
public const string fire_air_to_ground = "sim/weapons/fire_air_to_ground";           //Fire air-to-ground selection.
public const string fire_any_armed = "sim/weapons/fire_any_armed";           //Fire all armed selections.
public const string fire_any_shell = "sim/weapons/fire_any_shell";           //Fire selected weapon.
public const string GPS_lock_here = "sim/weapons/GPS_lock_here";           //Target camera pointer in GPS.
public const string weapon_target_down = "sim/weapons/weapon_target_down";           //Target select down.
public const string weapon_target_up = "sim/weapons/weapon_target_up";           //Target select up.
public const string deploy_chaff = "sim/weapons/deploy_chaff";           //Deploy chaff.
public const string deploy_flares = "sim/weapons/deploy_flares";           //Deploy flares.